"""
TODOBA Execution Plan

Represents an execution plan generated by the Brain
after validation has succeeded.

Version: 1.0
"""

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class ExecutionPlan:
    """
    Immutable execution plan.

    ExecutionWorker should execute this plan exactly as provided.
    """

    symbol: str
    order_type: str

    entry: Optional[float]

    sl: float
    tp: float

    lot: Optional[float]

    magic_number: int

    comment: str