"""
TODOBA Customer Registration Service

Owns durable pre-deployment commercial customer
registration state.

Trust boundary:

    registration_request_id
        -> durable registration request binding
        -> generated customer_id
        -> authoritative CustomerIdentity registration
        -> CustomerRegistrationResult

Identity rules:
- registration_request_id identifies one registration
  attempt
- customer_id is generated by TODOBA, never supplied by
  the caller
- identical retry returns the same customer_id
- one customer_id cannot belong to two registration
  requests
- the registration record is persisted before customer
  identity registration so retry can recover after an
  interruption

This owner deliberately represents only:

    registration_request_id
    customer_id

It does not:
- store email, phone, password, profile, or login data
- process payments, purchases, billing, or subscriptions
- activate setup rights or deployment entitlement
- accept or store MT5 account information
- create deployments or Trusted Agent identities
- issue customer access credentials
- build or deliver customer packages
- expose an HTTP API
"""

from dataclasses import dataclass
import json
import os
from pathlib import Path
import threading
import uuid

from backend.commercial.customer_identity_registry import (
    CustomerIdentity,
    CustomerIdentityRegistry,
)


STORE_VERSION = 1
_ID_GENERATION_ATTEMPTS = 128


@dataclass(
    frozen=True,
)
class CustomerRegistrationRecord:
    """
    Durable non-secret binding for one customer
    registration request.
    """

    registration_request_id: str
    customer_id: str

    def __post_init__(
        self,
    ) -> None:
        for name in (
            "registration_request_id",
            "customer_id",
        ):
            object.__setattr__(
                self,
                name,
                self._normalize_required_string(
                    getattr(
                        self,
                        name,
                    ),
                    name=name,
                ),
            )

    @staticmethod
    def _normalize_required_string(
        value: str,
        *,
        name: str,
    ) -> str:
        if not isinstance(
            value,
            str,
        ):
            raise TypeError(
                f"{name} must be str."
            )

        normalized = value.strip()

        if not normalized:
            raise ValueError(
                f"{name} is required."
            )

        return normalized


class CustomerRegistrationStore:
    """
    Durable authoritative owner of pre-deployment customer
    registration request bindings.

    One registration_request_id owns exactly one customer_id.
    One customer_id may belong to exactly one registration
    request.
    """

    def __init__(
        self,
        storage_path: Path,
    ) -> None:
        if not isinstance(
            storage_path,
            Path,
        ):
            raise TypeError(
                "storage_path must be Path."
            )

        self.storage_path = storage_path

        self._records: dict[
            str,
            CustomerRegistrationRecord,
        ] = {}

        self._request_id_by_customer_id: dict[
            str,
            str,
        ] = {}

        self._ready = False
        self._lock = threading.RLock()

        if self.storage_path.exists():
            self._restore_from_disk()

    def initialize_empty(
        self,
    ) -> None:
        """
        Explicitly initialize a new empty registration
        store.

        Missing durable storage is never silently treated as
        initialized commercial state.
        """

        with self._lock:
            if self._ready:
                return

            if self.storage_path.exists():
                self._restore_from_disk()
                return

            self._write_records(
                {}
            )

            self._records = {}
            self._request_id_by_customer_id = {}
            self._ready = True

    def is_ready(
        self,
    ) -> bool:
        return self._ready

    def register(
        self,
        record: CustomerRegistrationRecord,
    ) -> CustomerRegistrationRecord:
        """
        Persist one registration request binding.

        Identical retry is idempotent.
        Conflicting request reuse and customer reuse fail
        closed.
        """

        if not isinstance(
            record,
            CustomerRegistrationRecord,
        ):
            raise TypeError(
                "CustomerRegistrationStore requires "
                "CustomerRegistrationRecord."
            )

        with self._lock:
            self._require_ready()

            existing = self._records.get(
                record.registration_request_id
            )

            if existing is not None:
                if existing != record:
                    raise ValueError(
                        "Customer registration request is "
                        "already bound to a different "
                        "customer identity."
                    )

                return existing

            existing_request_id = (
                self._request_id_by_customer_id.get(
                    record.customer_id
                )
            )

            if existing_request_id is not None:
                raise ValueError(
                    "Customer identity is already bound "
                    "to another registration request."
                )

            candidate = dict(
                self._records
            )

            candidate[
                record.registration_request_id
            ] = record

            self._write_records(
                candidate
            )

            request_index = dict(
                self._request_id_by_customer_id
            )

            request_index[
                record.customer_id
            ] = record.registration_request_id

            self._records = candidate
            self._request_id_by_customer_id = (
                request_index
            )

            return record

    def get(
        self,
        *,
        registration_request_id: str,
    ) -> CustomerRegistrationRecord | None:
        self._require_ready()

        normalized_request_id = (
            CustomerRegistrationRecord
            ._normalize_required_string(
                registration_request_id,
                name="registration_request_id",
            )
        )

        return self._records.get(
            normalized_request_id
        )

    def get_by_customer_id(
        self,
        *,
        customer_id: str,
    ) -> CustomerRegistrationRecord | None:
        self._require_ready()

        normalized_customer_id = (
            CustomerRegistrationRecord
            ._normalize_required_string(
                customer_id,
                name="customer_id",
            )
        )

        request_id = (
            self._request_id_by_customer_id.get(
                normalized_customer_id
            )
        )

        if request_id is None:
            return None

        return self._records[
            request_id
        ]

    def all(
        self,
    ) -> tuple[
        CustomerRegistrationRecord,
        ...,
    ]:
        self._require_ready()

        return tuple(
            self._records[
                request_id
            ]
            for request_id in sorted(
                self._records
            )
        )

    def size(
        self,
    ) -> int:
        self._require_ready()

        return len(
            self._records
        )

    def _require_ready(
        self,
    ) -> None:
        if not self._ready:
            raise RuntimeError(
                "Customer registration store is not "
                "initialized."
            )

    def _restore_from_disk(
        self,
    ) -> None:
        payload = json.loads(
            self.storage_path.read_text(
                encoding="utf-8",
            )
        )

        if not isinstance(
            payload,
            dict,
        ):
            raise ValueError(
                "Customer registration payload must be "
                "an object."
            )

        if set(
            payload
        ) != {
            "version",
            "records",
        }:
            raise ValueError(
                "Customer registration payload has "
                "invalid fields."
            )

        if payload.get(
            "version"
        ) != STORE_VERSION:
            raise ValueError(
                "Unsupported customer registration "
                "store version."
            )

        items = payload.get(
            "records"
        )

        if not isinstance(
            items,
            list,
        ):
            raise ValueError(
                "Customer registration records must be "
                "a list."
            )

        restored: dict[
            str,
            CustomerRegistrationRecord,
        ] = {}

        customer_index: dict[
            str,
            str,
        ] = {}

        for item in items:
            if not isinstance(
                item,
                dict,
            ):
                raise ValueError(
                    "Customer registration item must be "
                    "an object."
                )

            if set(
                item
            ) != {
                "registration_request_id",
                "customer_id",
            }:
                raise ValueError(
                    "Customer registration item has "
                    "invalid fields."
                )

            record = CustomerRegistrationRecord(
                registration_request_id=item[
                    "registration_request_id"
                ],
                customer_id=item[
                    "customer_id"
                ],
            )

            if (
                record.registration_request_id
                in restored
            ):
                raise ValueError(
                    "Duplicate customer registration "
                    "request."
                )

            if (
                record.customer_id
                in customer_index
            ):
                raise ValueError(
                    "Customer identity is bound to "
                    "multiple registration requests."
                )

            restored[
                record.registration_request_id
            ] = record

            customer_index[
                record.customer_id
            ] = record.registration_request_id

        self._records = restored
        self._request_id_by_customer_id = (
            customer_index
        )
        self._ready = True

    def _write_records(
        self,
        records: dict[
            str,
            CustomerRegistrationRecord,
        ],
    ) -> None:
        items = []

        for request_id in sorted(
            records
        ):
            record = records[
                request_id
            ]

            items.append(
                {
                    "registration_request_id": (
                        record.registration_request_id
                    ),
                    "customer_id": (
                        record.customer_id
                    ),
                }
            )

        payload = {
            "version": STORE_VERSION,
            "records": items,
        }

        self.storage_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        temporary_path = (
            self.storage_path.with_name(
                f"{self.storage_path.name}.tmp"
            )
        )

        try:
            temporary_path.write_text(
                json.dumps(
                    payload,
                    indent=2,
                    sort_keys=True,
                )
                + "\n",
                encoding="utf-8",
            )

            os.replace(
                temporary_path,
                self.storage_path,
            )
        except Exception:
            if temporary_path.exists():
                temporary_path.unlink()

            raise


@dataclass(
    frozen=True,
)
class CustomerRegistrationResult:
    """
    Safe result for one completed customer registration.
    """

    registration_request_id: str
    customer_id: str

    def __post_init__(
        self,
    ) -> None:
        for name in (
            "registration_request_id",
            "customer_id",
        ):
            object.__setattr__(
                self,
                name,
                CustomerRegistrationRecord
                ._normalize_required_string(
                    getattr(
                        self,
                        name,
                    ),
                    name=name,
                ),
            )


class CustomerRegistrationService:
    """
    Create or recover one durable commercial customer
    identity from one registration request.
    """

    def __init__(
        self,
        *,
        registration_store: CustomerRegistrationStore,
        customer_identity_registry: (
            CustomerIdentityRegistry
        ),
    ) -> None:
        if not isinstance(
            registration_store,
            CustomerRegistrationStore,
        ):
            raise TypeError(
                "registration_store must be "
                "CustomerRegistrationStore."
            )

        if not isinstance(
            customer_identity_registry,
            CustomerIdentityRegistry,
        ):
            raise TypeError(
                "customer_identity_registry must be "
                "CustomerIdentityRegistry."
            )

        if not registration_store.is_ready():
            raise RuntimeError(
                "Customer registration store is not "
                "initialized."
            )

        if not customer_identity_registry.is_ready():
            raise RuntimeError(
                "Customer identity registry is not "
                "initialized."
            )

        self._registration_store = (
            registration_store
        )

        self._customer_identity_registry = (
            customer_identity_registry
        )

        self._lock = threading.RLock()

    def register(
        self,
        *,
        registration_request_id: str,
    ) -> CustomerRegistrationResult:
        """
        Register one commercial customer.

        Retry contract:
        - same request returns the same customer_id
        - persisted registration survives interruption
        - missing downstream CustomerIdentity is repaired on
          retry using the persisted customer_id
        """

        normalized_request_id = (
            CustomerRegistrationRecord
            ._normalize_required_string(
                registration_request_id,
                name="registration_request_id",
            )
        )

        with self._lock:
            self._require_sources_ready()

            record = (
                self._registration_store.get(
                    registration_request_id=(
                        normalized_request_id
                    )
                )
            )

            if record is None:
                record = (
                    self._create_registration_record(
                        registration_request_id=(
                            normalized_request_id
                        )
                    )
                )

            identity = (
                self._customer_identity_registry.register(
                    CustomerIdentity(
                        customer_id=record.customer_id
                    )
                )
            )

            if (
                identity.customer_id
                != record.customer_id
            ):
                raise RuntimeError(
                    "Customer identity registration "
                    "returned mismatched identity."
                )

            return CustomerRegistrationResult(
                registration_request_id=(
                    record.registration_request_id
                ),
                customer_id=(
                    identity.customer_id
                ),
            )

    def _create_registration_record(
        self,
        *,
        registration_request_id: str,
    ) -> CustomerRegistrationRecord:
        for _ in range(
            _ID_GENERATION_ATTEMPTS
        ):
            customer_id = (
                f"customer-{uuid.uuid4().hex}"
            )

            if (
                self._registration_store
                .get_by_customer_id(
                    customer_id=customer_id
                )
                is not None
            ):
                continue

            if (
                self._customer_identity_registry.contains(
                    customer_id=customer_id
                )
            ):
                continue

            record = CustomerRegistrationRecord(
                registration_request_id=(
                    registration_request_id
                ),
                customer_id=customer_id,
            )

            return self._registration_store.register(
                record
            )

        raise RuntimeError(
            "Unable to generate unique customer identity."
        )

    def _require_sources_ready(
        self,
    ) -> None:
        if not self._registration_store.is_ready():
            raise RuntimeError(
                "Customer registration store is not "
                "initialized."
            )

        if not self._customer_identity_registry.is_ready():
            raise RuntimeError(
                "Customer identity registry is not "
                "initialized."
            )