"""
TODOBA Customer Commercial Order Service

Owns durable pre-payment commercial order truth.

Trust boundary:

    authoritative CustomerIdentity
        -> order_request_id
        -> generated order_id
        -> immutable expected amount_minor
        -> immutable currency
        -> PENDING

Security rules:
- customer identity must already exist in CustomerIdentityRegistry
- customer_id comes only from authoritative CustomerIdentity
- order_id is generated by TODOBA
- order_request_id is the idempotency identity
- identical retry returns the same order
- one order request cannot move to another customer
- one order request cannot change amount or currency
- amount_minor is a positive integer; bool and float are rejected
- currency is normalized to uppercase three-letter ASCII
- durable state is written before RAM advances

This owner deliberately does not:
- create payment intents
- select payment rails
- process bank or provider evidence
- verify callbacks or webhooks
- mark payments paid or settled
- store provider transaction identifiers
- store payment credentials or secrets
- grant setup activation
- mutate deployment entitlement
- expose an HTTP API
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import json
import os
from pathlib import Path
import threading
import uuid

from backend.commercial.customer_identity_registry import (
    CustomerIdentity,
    CustomerIdentityRegistry,
)


STORE_VERSION = 1
_ID_GENERATION_ATTEMPTS = 128


class CustomerCommercialOrderStatus(
    str,
    Enum,
):
    PENDING = "PENDING"


@dataclass(
    frozen=True,
)
class CustomerCommercialOrderRecord:
    """
    Immutable durable truth for one pre-payment commercial order.
    """

    order_request_id: str
    order_id: str
    customer_id: str
    amount_minor: int
    currency: str
    status: CustomerCommercialOrderStatus

    def __post_init__(
        self,
    ) -> None:
        for name in (
            "order_request_id",
            "order_id",
            "customer_id",
        ):
            object.__setattr__(
                self,
                name,
                self._normalize_required_string(
                    getattr(
                        self,
                        name,
                    ),
                    name=name,
                ),
            )

        object.__setattr__(
            self,
            "amount_minor",
            self._normalize_amount_minor(
                self.amount_minor
            ),
        )

        object.__setattr__(
            self,
            "currency",
            self._normalize_currency(
                self.currency
            ),
        )

        if not isinstance(
            self.status,
            CustomerCommercialOrderStatus,
        ):
            raise TypeError(
                "status must be "
                "CustomerCommercialOrderStatus."
            )

        if (
            self.status
            is not CustomerCommercialOrderStatus.PENDING
        ):
            raise ValueError(
                "Unsupported customer commercial "
                "order status."
            )

    @staticmethod
    def _normalize_required_string(
        value: str,
        *,
        name: str,
    ) -> str:
        if not isinstance(
            value,
            str,
        ):
            raise TypeError(
                f"{name} must be str."
            )

        normalized = value.strip()

        if not normalized:
            raise ValueError(
                f"{name} is required."
            )

        return normalized

    @staticmethod
    def _normalize_amount_minor(
        value: int,
    ) -> int:
        if (
            isinstance(
                value,
                bool,
            )
            or not isinstance(
                value,
                int,
            )
        ):
            raise TypeError(
                "amount_minor must be int."
            )

        if value <= 0:
            raise ValueError(
                "amount_minor must be positive."
            )

        return value

    @staticmethod
    def _normalize_currency(
        value: str,
    ) -> str:
        if not isinstance(
            value,
            str,
        ):
            raise TypeError(
                "currency must be str."
            )

        normalized = value.strip().upper()

        if (
            len(normalized) != 3
            or not normalized.isascii()
            or not normalized.isalpha()
        ):
            raise ValueError(
                "currency must be a three-letter "
                "ASCII currency code."
            )

        return normalized


@dataclass(
    frozen=True,
)
class CustomerCommercialOrderResult:
    """
    Safe non-secret result for one commercial order.
    """

    order_request_id: str
    order_id: str
    customer_id: str
    amount_minor: int
    currency: str
    status: CustomerCommercialOrderStatus

    def __post_init__(
        self,
    ) -> None:
        validated = CustomerCommercialOrderRecord(
            order_request_id=self.order_request_id,
            order_id=self.order_id,
            customer_id=self.customer_id,
            amount_minor=self.amount_minor,
            currency=self.currency,
            status=self.status,
        )

        object.__setattr__(
            self,
            "order_request_id",
            validated.order_request_id,
        )
        object.__setattr__(
            self,
            "order_id",
            validated.order_id,
        )
        object.__setattr__(
            self,
            "customer_id",
            validated.customer_id,
        )
        object.__setattr__(
            self,
            "amount_minor",
            validated.amount_minor,
        )
        object.__setattr__(
            self,
            "currency",
            validated.currency,
        )
        object.__setattr__(
            self,
            "status",
            validated.status,
        )


class CustomerCommercialOrderStore:
    """
    Durable authoritative owner of commercial order records.

    Primary identity:
        order_id

    Idempotency identity:
        order_request_id
    """

    def __init__(
        self,
        storage_path: Path,
    ) -> None:
        if not isinstance(
            storage_path,
            Path,
        ):
            raise TypeError(
                "storage_path must be Path."
            )

        self.storage_path = storage_path

        self._records: dict[
            str,
            CustomerCommercialOrderRecord,
        ] = {}

        self._order_id_by_request_id: dict[
            str,
            str,
        ] = {}

        self._ready = False
        self._lock = threading.RLock()

        if self.storage_path.exists():
            self._restore_from_disk()

    def initialize_empty(
        self,
    ) -> None:
        with self._lock:
            if self._ready:
                return

            if self.storage_path.exists():
                self._restore_from_disk()
                return

            self._write_records(
                {}
            )

            self._records = {}
            self._order_id_by_request_id = {}
            self._ready = True

    def open_existing(
        self,
    ) -> None:
        with self._lock:
            if not self.storage_path.exists():
                raise RuntimeError(
                    "Customer commercial order store "
                    "does not exist."
                )

            if self._ready:
                return

            self._restore_from_disk()

    def is_ready(
        self,
    ) -> bool:
        return self._ready

    def register(
        self,
        record: CustomerCommercialOrderRecord,
    ) -> CustomerCommercialOrderRecord:
        if not isinstance(
            record,
            CustomerCommercialOrderRecord,
        ):
            raise TypeError(
                "CustomerCommercialOrderStore requires "
                "CustomerCommercialOrderRecord."
            )

        with self._lock:
            self._require_ready()

            existing_id = (
                self._order_id_by_request_id.get(
                    record.order_request_id
                )
            )

            if existing_id is not None:
                existing = self._records[
                    existing_id
                ]

                if existing != record:
                    raise ValueError(
                        "Customer commercial order request "
                        "is already bound to different "
                        "commercial facts."
                    )

                return existing

            existing = self._records.get(
                record.order_id
            )

            if existing is not None:
                if existing != record:
                    raise ValueError(
                        "Customer commercial order ID "
                        "already exists."
                    )

                return existing

            candidate = dict(
                self._records
            )

            candidate[
                record.order_id
            ] = record

            self._write_records(
                candidate
            )

            request_index = dict(
                self._order_id_by_request_id
            )
            request_index[
                record.order_request_id
            ] = record.order_id

            self._records = candidate
            self._order_id_by_request_id = (
                request_index
            )

            return record

    def get(
        self,
        *,
        order_id: str,
    ) -> CustomerCommercialOrderRecord | None:
        self._require_ready()

        normalized = (
            CustomerCommercialOrderRecord
            ._normalize_required_string(
                order_id,
                name="order_id",
            )
        )

        return self._records.get(
            normalized
        )

    def get_by_order_request_id(
        self,
        *,
        order_request_id: str,
    ) -> CustomerCommercialOrderRecord | None:
        self._require_ready()

        normalized = (
            CustomerCommercialOrderRecord
            ._normalize_required_string(
                order_request_id,
                name="order_request_id",
            )
        )

        order_id = (
            self._order_id_by_request_id.get(
                normalized
            )
        )

        if order_id is None:
            return None

        return self._records[
            order_id
        ]

    def all(
        self,
    ) -> tuple[
        CustomerCommercialOrderRecord,
        ...,
    ]:
        self._require_ready()

        return tuple(
            self._records[
                order_id
            ]
            for order_id in sorted(
                self._records
            )
        )

    def size(
        self,
    ) -> int:
        self._require_ready()

        return len(
            self._records
        )

    def _require_ready(
        self,
    ) -> None:
        if not self._ready:
            raise RuntimeError(
                "Customer commercial order store "
                "is not initialized."
            )

    def _restore_from_disk(
        self,
    ) -> None:
        try:
            payload = json.loads(
                self.storage_path.read_text(
                    encoding="utf-8",
                )
            )
        except (
            OSError,
            UnicodeError,
            json.JSONDecodeError,
        ) as exc:
            raise ValueError(
                "Customer commercial order store "
                "is unreadable."
            ) from exc

        if not isinstance(
            payload,
            dict,
        ):
            raise ValueError(
                "Customer commercial order store "
                "must contain an object."
            )

        if set(
            payload
        ) != {
            "version",
            "records",
        }:
            raise ValueError(
                "Customer commercial order store "
                "has invalid fields."
            )

        if payload[
            "version"
        ] != STORE_VERSION:
            raise ValueError(
                "Unsupported customer commercial "
                "order store version."
            )

        items = payload[
            "records"
        ]

        if not isinstance(
            items,
            list,
        ):
            raise ValueError(
                "Customer commercial order records "
                "must be a list."
            )

        restored: dict[
            str,
            CustomerCommercialOrderRecord,
        ] = {}

        request_index: dict[
            str,
            str,
        ] = {}

        for item in items:
            if not isinstance(
                item,
                dict,
            ):
                raise ValueError(
                    "Customer commercial order item "
                    "must be an object."
                )

            if set(
                item
            ) != {
                "order_request_id",
                "order_id",
                "customer_id",
                "amount_minor",
                "currency",
                "status",
            }:
                raise ValueError(
                    "Customer commercial order item "
                    "has invalid fields."
                )

            try:
                record = (
                    CustomerCommercialOrderRecord(
                        order_request_id=item[
                            "order_request_id"
                        ],
                        order_id=item[
                            "order_id"
                        ],
                        customer_id=item[
                            "customer_id"
                        ],
                        amount_minor=item[
                            "amount_minor"
                        ],
                        currency=item[
                            "currency"
                        ],
                        status=(
                            CustomerCommercialOrderStatus(
                                item[
                                    "status"
                                ]
                            )
                        ),
                    )
                )
            except (
                TypeError,
                ValueError,
            ) as exc:
                raise ValueError(
                    "Customer commercial order item "
                    "is invalid."
                ) from exc

            if record.order_id in restored:
                raise ValueError(
                    "Duplicate customer commercial "
                    "order ID."
                )

            if (
                record.order_request_id
                in request_index
            ):
                raise ValueError(
                    "Duplicate customer commercial "
                    "order request."
                )

            restored[
                record.order_id
            ] = record

            request_index[
                record.order_request_id
            ] = record.order_id

        self._records = restored
        self._order_id_by_request_id = (
            request_index
        )
        self._ready = True

    def _write_records(
        self,
        records: dict[
            str,
            CustomerCommercialOrderRecord,
        ],
    ) -> None:
        items = []

        for order_id in sorted(
            records
        ):
            record = records[
                order_id
            ]

            items.append(
                {
                    "order_request_id": (
                        record.order_request_id
                    ),
                    "order_id": (
                        record.order_id
                    ),
                    "customer_id": (
                        record.customer_id
                    ),
                    "amount_minor": (
                        record.amount_minor
                    ),
                    "currency": (
                        record.currency
                    ),
                    "status": (
                        record.status.value
                    ),
                }
            )

        payload = {
            "version": STORE_VERSION,
            "records": items,
        }

        self.storage_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        temporary_path = (
            self.storage_path.with_name(
                f".{self.storage_path.name}."
                f"{uuid.uuid4().hex}.tmp"
            )
        )

        try:
            with temporary_path.open(
                "w",
                encoding="utf-8",
                newline="\n",
            ) as destination:
                json.dump(
                    payload,
                    destination,
                    ensure_ascii=False,
                    indent=2,
                    sort_keys=True,
                )
                destination.write(
                    "\n"
                )
                destination.flush()
                os.fsync(
                    destination.fileno()
                )

            os.replace(
                temporary_path,
                self.storage_path,
            )
        finally:
            if temporary_path.exists():
                temporary_path.unlink()


class CustomerCommercialOrderService:
    """
    Create or recover one authoritative pre-payment order.
    """

    def __init__(
        self,
        *,
        order_store: CustomerCommercialOrderStore,
        customer_identity_registry: (
            CustomerIdentityRegistry
        ),
    ) -> None:
        if not isinstance(
            order_store,
            CustomerCommercialOrderStore,
        ):
            raise TypeError(
                "order_store must be "
                "CustomerCommercialOrderStore."
            )

        if not isinstance(
            customer_identity_registry,
            CustomerIdentityRegistry,
        ):
            raise TypeError(
                "customer_identity_registry must be "
                "CustomerIdentityRegistry."
            )

        if not order_store.is_ready():
            raise RuntimeError(
                "Customer commercial order store "
                "is not initialized."
            )

        if not customer_identity_registry.is_ready():
            raise RuntimeError(
                "Customer identity registry "
                "is not initialized."
            )

        self._order_store = order_store
        self._customer_identity_registry = (
            customer_identity_registry
        )
        self._lock = threading.RLock()

    def create(
        self,
        *,
        order_request_id: str,
        authorized_customer: CustomerIdentity,
        amount_minor: int,
        currency: str,
    ) -> CustomerCommercialOrderResult:
        normalized_request_id = (
            CustomerCommercialOrderRecord
            ._normalize_required_string(
                order_request_id,
                name="order_request_id",
            )
        )

        if not isinstance(
            authorized_customer,
            CustomerIdentity,
        ):
            raise TypeError(
                "authorized_customer must be "
                "CustomerIdentity."
            )

        normalized_amount = (
            CustomerCommercialOrderRecord
            ._normalize_amount_minor(
                amount_minor
            )
        )

        normalized_currency = (
            CustomerCommercialOrderRecord
            ._normalize_currency(
                currency
            )
        )

        with self._lock:
            self._require_sources_ready()

            authoritative_customer = (
                self._customer_identity_registry.get(
                    customer_id=(
                        authorized_customer.customer_id
                    )
                )
            )

            if (
                authoritative_customer is None
                or authoritative_customer
                != authorized_customer
            ):
                raise ValueError(
                    "Customer identity is not "
                    "authoritative."
                )

            existing = (
                self._order_store
                .get_by_order_request_id(
                    order_request_id=(
                        normalized_request_id
                    )
                )
            )

            if existing is not None:
                if (
                    existing.customer_id
                    != authoritative_customer.customer_id
                    or existing.amount_minor
                    != normalized_amount
                    or existing.currency
                    != normalized_currency
                ):
                    raise ValueError(
                        "Customer commercial order request "
                        "is already bound to different "
                        "commercial facts."
                    )

                return self._build_result(
                    existing
                )

            record = self._create_pending_record(
                order_request_id=(
                    normalized_request_id
                ),
                customer_id=(
                    authoritative_customer.customer_id
                ),
                amount_minor=normalized_amount,
                currency=normalized_currency,
            )

            stored = self._order_store.register(
                record
            )

            return self._build_result(
                stored
            )

    def get(
        self,
        *,
        order_id: str,
    ) -> CustomerCommercialOrderResult | None:
        self._require_sources_ready()

        record = self._order_store.get(
            order_id=order_id
        )

        if record is None:
            return None

        return self._build_result(
            record
        )

    def _create_pending_record(
        self,
        *,
        order_request_id: str,
        customer_id: str,
        amount_minor: int,
        currency: str,
    ) -> CustomerCommercialOrderRecord:
        for _ in range(
            _ID_GENERATION_ATTEMPTS
        ):
            order_id = (
                f"commercial-order-{uuid.uuid4().hex}"
            )

            if (
                self._order_store.get(
                    order_id=order_id
                )
                is not None
            ):
                continue

            return CustomerCommercialOrderRecord(
                order_request_id=(
                    order_request_id
                ),
                order_id=order_id,
                customer_id=customer_id,
                amount_minor=amount_minor,
                currency=currency,
                status=(
                    CustomerCommercialOrderStatus.PENDING
                ),
            )

        raise RuntimeError(
            "Unable to generate unique customer "
            "commercial order identity."
        )

    def _require_sources_ready(
        self,
    ) -> None:
        if not self._order_store.is_ready():
            raise RuntimeError(
                "Customer commercial order store "
                "is not initialized."
            )

        if not self._customer_identity_registry.is_ready():
            raise RuntimeError(
                "Customer identity registry "
                "is not initialized."
            )

    @staticmethod
    def _build_result(
        record: CustomerCommercialOrderRecord,
    ) -> CustomerCommercialOrderResult:
        return CustomerCommercialOrderResult(
            order_request_id=(
                record.order_request_id
            ),
            order_id=record.order_id,
            customer_id=record.customer_id,
            amount_minor=record.amount_minor,
            currency=record.currency,
            status=record.status,
        )
