"""
TODOBA Customer Registration API

Public pre-authorization commercial identity entry boundary.

Trust flow:

    registration_request_id
        -> CustomerRegistrationService.register()
        -> authoritative customer_id

Security and ownership rules:
- caller supplies only registration_request_id
- customer_id is generated by CustomerRegistrationService
- registration retry/idempotency remains owned by that service
- no setup activation is granted here
- no setup handoff credential is issued here
- no customer access credential is issued here
- no payment or subscription state is accepted or mutated here
- no deployment, entitlement, MT5, package, or runtime state is
  accepted or mutated here
"""

from __future__ import annotations

from fastapi import APIRouter
from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import field_validator

from backend.commercial.customer_registration_service import (
    CustomerRegistrationResult,
)


_REGISTRATION_PATH = (
    "/customer/register"
)


class CustomerRegistrationRequest(
    BaseModel
):
    """
    The only customer-controlled registration payload.
    """

    model_config = ConfigDict(
        extra="forbid",
    )

    registration_request_id: str

    @field_validator(
        "registration_request_id"
    )
    @classmethod
    def normalize_registration_request_id(
        cls,
        value: str,
    ) -> str:
        normalized = value.strip()

        if not normalized:
            raise ValueError(
                "registration_request_id is required."
            )

        return normalized


class CustomerRegistrationResponse(
    BaseModel
):
    """
    Customer-safe authoritative registration result.
    """

    model_config = ConfigDict(
        extra="forbid",
    )

    registration_request_id: str
    customer_id: str


def create_customer_registration_router(
    *,
    registration_service,
) -> APIRouter:
    """
    Build the public customer registration router from the
    already-composed authoritative registration owner.
    """

    _require_owner_method(
        registration_service,
        owner_name="registration_service",
        method_name="register",
    )

    router = APIRouter()

    @router.post(
        _REGISTRATION_PATH,
        response_model=(
            CustomerRegistrationResponse
        ),
    )
    def register_customer(
        request: CustomerRegistrationRequest,
    ) -> CustomerRegistrationResponse:
        result = (
            registration_service.register(
                registration_request_id=(
                    request.registration_request_id
                )
            )
        )

        if not isinstance(
            result,
            CustomerRegistrationResult,
        ):
            raise RuntimeError(
                "Customer registration service returned "
                "invalid result."
            )

        if (
            result.registration_request_id
            != request.registration_request_id
        ):
            raise RuntimeError(
                "Customer registration request identity "
                "did not converge."
            )

        return CustomerRegistrationResponse(
            registration_request_id=(
                result.registration_request_id
            ),
            customer_id=(
                result.customer_id
            ),
        )

    return router


def _require_owner_method(
    owner,
    *,
    owner_name: str,
    method_name: str,
) -> None:
    method = getattr(
        owner,
        method_name,
        None,
    )

    if not callable(
        method
    ):
        raise TypeError(
            f"{owner_name} must expose callable "
            f"{method_name}()."
        )
