"""
TODOBA Customer Payment Evidence Service

Owns durable normalized payment-evidence intake truth.

Trust boundary:

    authoritative CustomerPaymentIntentResult
        -> evidence_request_id
        -> generated payment_evidence_id
        -> evidence_source
        -> external_evidence_id
        -> RECEIVED

Replay identity:

    (evidence_source, external_evidence_id)

Security rules:
- payment intent must exist exactly in CustomerPaymentIntentStore
- evidence source must match the payment intent rail
- payment_evidence_id is generated by TODOBA
- evidence_request_id is an idempotency identity
- identical request retry returns the same evidence
- one request cannot change evidence facts
- one replay identity cannot move to another payment intent
- repeated replay identity for the same intent deduplicates
- durable state is written before RAM advances

This owner deliberately does not:
- verify provider authenticity
- verify webhook signatures
- call PayPal or bank APIs
- process raw callbacks or webhooks
- store raw provider payloads
- store payment credentials or secrets
- duplicate order amount or currency
- mark payment paid or settled
- grant setup activation
- mutate deployment entitlement
- expose an HTTP API
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import json
import os
from pathlib import Path
import threading
import uuid

from backend.commercial.customer_payment_intent_service import (
    CustomerPaymentIntentResult,
    CustomerPaymentIntentStatus,
    CustomerPaymentIntentStore,
    PaymentRail,
)


STORE_VERSION = 1
_ID_GENERATION_ATTEMPTS = 128


class PaymentEvidenceSource(
    str,
    Enum,
):
    PAYPAL = "PAYPAL"
    VND_BANK_TRANSFER = "VND_BANK_TRANSFER"


class CustomerPaymentEvidenceStatus(
    str,
    Enum,
):
    RECEIVED = "RECEIVED"


@dataclass(
    frozen=True,
)
class CustomerPaymentEvidenceRecord:
    """
    Immutable normalized payment evidence binding.
    """

    evidence_request_id: str
    payment_evidence_id: str
    payment_intent_id: str
    evidence_source: PaymentEvidenceSource
    external_evidence_id: str
    status: CustomerPaymentEvidenceStatus

    def __post_init__(
        self,
    ) -> None:
        for name in (
            "evidence_request_id",
            "payment_evidence_id",
            "payment_intent_id",
            "external_evidence_id",
        ):
            object.__setattr__(
                self,
                name,
                self._normalize_required_string(
                    getattr(
                        self,
                        name,
                    ),
                    name=name,
                ),
            )

        if not isinstance(
            self.evidence_source,
            PaymentEvidenceSource,
        ):
            raise TypeError(
                "evidence_source must be "
                "PaymentEvidenceSource."
            )

        if not isinstance(
            self.status,
            CustomerPaymentEvidenceStatus,
        ):
            raise TypeError(
                "status must be "
                "CustomerPaymentEvidenceStatus."
            )

        if (
            self.status
            is not CustomerPaymentEvidenceStatus.RECEIVED
        ):
            raise ValueError(
                "Unsupported customer payment "
                "evidence status."
            )

    @staticmethod
    def _normalize_required_string(
        value: str,
        *,
        name: str,
    ) -> str:
        if not isinstance(
            value,
            str,
        ):
            raise TypeError(
                f"{name} must be str."
            )

        normalized = value.strip()

        if not normalized:
            raise ValueError(
                f"{name} is required."
            )

        return normalized


class CustomerPaymentEvidenceStore:
    """
    Durable authoritative owner of normalized payment evidence.

    Primary identity:
        payment_evidence_id

    Idempotency identity:
        evidence_request_id

    Replay identity:
        (evidence_source, external_evidence_id)
    """

    def __init__(
        self,
        storage_path: Path,
    ) -> None:
        if not isinstance(
            storage_path,
            Path,
        ):
            raise TypeError(
                "storage_path must be Path."
            )

        self.storage_path = storage_path

        self._records: dict[
            str,
            CustomerPaymentEvidenceRecord,
        ] = {}

        self._evidence_id_by_request_id: dict[
            str,
            str,
        ] = {}

        self._evidence_id_by_replay_key: dict[
            tuple[
                PaymentEvidenceSource,
                str,
            ],
            str,
        ] = {}

        self._ready = False
        self._lock = threading.RLock()

        if self.storage_path.exists():
            self._restore_from_disk()

    def initialize_empty(
        self,
    ) -> None:
        with self._lock:
            if self._ready:
                return

            if self.storage_path.exists():
                self._restore_from_disk()
                return

            self._write_records(
                {}
            )

            self._records = {}
            self._evidence_id_by_request_id = {}
            self._evidence_id_by_replay_key = {}
            self._ready = True

    def open_existing(
        self,
    ) -> None:
        with self._lock:
            if not self.storage_path.exists():
                raise RuntimeError(
                    "Customer payment evidence store "
                    "does not exist."
                )

            if self._ready:
                return

            self._restore_from_disk()

    def is_ready(
        self,
    ) -> bool:
        return self._ready

    def register(
        self,
        record: CustomerPaymentEvidenceRecord,
    ) -> CustomerPaymentEvidenceRecord:
        if not isinstance(
            record,
            CustomerPaymentEvidenceRecord,
        ):
            raise TypeError(
                "CustomerPaymentEvidenceStore requires "
                "CustomerPaymentEvidenceRecord."
            )

        with self._lock:
            self._require_ready()

            existing_id = (
                self._evidence_id_by_request_id.get(
                    record.evidence_request_id
                )
            )

            if existing_id is not None:
                existing = self._records[
                    existing_id
                ]

                if existing != record:
                    raise ValueError(
                        "Customer payment evidence request "
                        "is already bound to different "
                        "evidence facts."
                    )

                return existing

            replay_key = (
                record.evidence_source,
                record.external_evidence_id,
            )

            replay_id = (
                self._evidence_id_by_replay_key.get(
                    replay_key
                )
            )

            if replay_id is not None:
                existing = self._records[
                    replay_id
                ]

                if (
                    existing.payment_intent_id
                    != record.payment_intent_id
                ):
                    raise ValueError(
                        "Payment evidence replay identity "
                        "is already bound to another "
                        "payment intent."
                    )

                return existing

            existing = self._records.get(
                record.payment_evidence_id
            )

            if existing is not None:
                if existing != record:
                    raise ValueError(
                        "Customer payment evidence ID "
                        "already exists."
                    )

                return existing

            candidate = dict(
                self._records
            )
            candidate[
                record.payment_evidence_id
            ] = record

            self._write_records(
                candidate
            )

            request_index = dict(
                self._evidence_id_by_request_id
            )
            request_index[
                record.evidence_request_id
            ] = record.payment_evidence_id

            replay_index = dict(
                self._evidence_id_by_replay_key
            )
            replay_index[
                replay_key
            ] = record.payment_evidence_id

            self._records = candidate
            self._evidence_id_by_request_id = (
                request_index
            )
            self._evidence_id_by_replay_key = (
                replay_index
            )

            return record

    def get(
        self,
        *,
        payment_evidence_id: str,
    ) -> CustomerPaymentEvidenceRecord | None:
        self._require_ready()

        normalized = (
            CustomerPaymentEvidenceRecord
            ._normalize_required_string(
                payment_evidence_id,
                name="payment_evidence_id",
            )
        )

        return self._records.get(
            normalized
        )

    def get_by_evidence_request_id(
        self,
        *,
        evidence_request_id: str,
    ) -> CustomerPaymentEvidenceRecord | None:
        self._require_ready()

        normalized = (
            CustomerPaymentEvidenceRecord
            ._normalize_required_string(
                evidence_request_id,
                name="evidence_request_id",
            )
        )

        payment_evidence_id = (
            self._evidence_id_by_request_id.get(
                normalized
            )
        )

        if payment_evidence_id is None:
            return None

        return self._records[
            payment_evidence_id
        ]

    def get_by_replay_identity(
        self,
        *,
        evidence_source: PaymentEvidenceSource,
        external_evidence_id: str,
    ) -> CustomerPaymentEvidenceRecord | None:
        self._require_ready()

        if not isinstance(
            evidence_source,
            PaymentEvidenceSource,
        ):
            raise TypeError(
                "evidence_source must be "
                "PaymentEvidenceSource."
            )

        normalized_external_id = (
            CustomerPaymentEvidenceRecord
            ._normalize_required_string(
                external_evidence_id,
                name="external_evidence_id",
            )
        )

        payment_evidence_id = (
            self._evidence_id_by_replay_key.get(
                (
                    evidence_source,
                    normalized_external_id,
                )
            )
        )

        if payment_evidence_id is None:
            return None

        return self._records[
            payment_evidence_id
        ]

    def all(
        self,
    ) -> tuple[
        CustomerPaymentEvidenceRecord,
        ...,
    ]:
        self._require_ready()

        return tuple(
            self._records[
                evidence_id
            ]
            for evidence_id in sorted(
                self._records
            )
        )

    def size(
        self,
    ) -> int:
        self._require_ready()
        return len(
            self._records
        )

    def _require_ready(
        self,
    ) -> None:
        if not self._ready:
            raise RuntimeError(
                "Customer payment evidence store "
                "is not initialized."
            )

    def _restore_from_disk(
        self,
    ) -> None:
        try:
            payload = json.loads(
                self.storage_path.read_text(
                    encoding="utf-8",
                )
            )
        except (
            OSError,
            UnicodeError,
            json.JSONDecodeError,
        ) as exc:
            raise ValueError(
                "Customer payment evidence store "
                "is unreadable."
            ) from exc

        if not isinstance(
            payload,
            dict,
        ):
            raise ValueError(
                "Customer payment evidence store "
                "must contain an object."
            )

        if set(
            payload
        ) != {
            "version",
            "records",
        }:
            raise ValueError(
                "Customer payment evidence store "
                "has invalid fields."
            )

        if (
            payload["version"]
            != STORE_VERSION
        ):
            raise ValueError(
                "Unsupported customer payment "
                "evidence store version."
            )

        items = payload[
            "records"
        ]

        if not isinstance(
            items,
            list,
        ):
            raise ValueError(
                "Customer payment evidence records "
                "must be a list."
            )

        restored: dict[
            str,
            CustomerPaymentEvidenceRecord,
        ] = {}

        request_index: dict[
            str,
            str,
        ] = {}

        replay_index: dict[
            tuple[
                PaymentEvidenceSource,
                str,
            ],
            str,
        ] = {}

        for item in items:
            if not isinstance(
                item,
                dict,
            ):
                raise ValueError(
                    "Customer payment evidence item "
                    "must be an object."
                )

            if set(
                item
            ) != {
                "evidence_request_id",
                "payment_evidence_id",
                "payment_intent_id",
                "evidence_source",
                "external_evidence_id",
                "status",
            }:
                raise ValueError(
                    "Customer payment evidence item "
                    "has invalid fields."
                )

            try:
                record = CustomerPaymentEvidenceRecord(
                    evidence_request_id=item[
                        "evidence_request_id"
                    ],
                    payment_evidence_id=item[
                        "payment_evidence_id"
                    ],
                    payment_intent_id=item[
                        "payment_intent_id"
                    ],
                    evidence_source=(
                        PaymentEvidenceSource(
                            item[
                                "evidence_source"
                            ]
                        )
                    ),
                    external_evidence_id=item[
                        "external_evidence_id"
                    ],
                    status=(
                        CustomerPaymentEvidenceStatus(
                            item[
                                "status"
                            ]
                        )
                    ),
                )
            except (
                TypeError,
                ValueError,
            ) as exc:
                raise ValueError(
                    "Customer payment evidence item "
                    "is invalid."
                ) from exc

            if (
                record.payment_evidence_id
                in restored
            ):
                raise ValueError(
                    "Duplicate customer payment "
                    "evidence ID."
                )

            if (
                record.evidence_request_id
                in request_index
            ):
                raise ValueError(
                    "Duplicate customer payment "
                    "evidence request."
                )

            replay_key = (
                record.evidence_source,
                record.external_evidence_id,
            )

            if replay_key in replay_index:
                raise ValueError(
                    "Duplicate customer payment "
                    "evidence replay identity."
                )

            restored[
                record.payment_evidence_id
            ] = record

            request_index[
                record.evidence_request_id
            ] = record.payment_evidence_id

            replay_index[
                replay_key
            ] = record.payment_evidence_id

        self._records = restored
        self._evidence_id_by_request_id = (
            request_index
        )
        self._evidence_id_by_replay_key = (
            replay_index
        )
        self._ready = True

    def _write_records(
        self,
        records: dict[
            str,
            CustomerPaymentEvidenceRecord,
        ],
    ) -> None:
        items = []

        for evidence_id in sorted(
            records
        ):
            record = records[
                evidence_id
            ]

            items.append(
                {
                    "evidence_request_id": (
                        record.evidence_request_id
                    ),
                    "payment_evidence_id": (
                        record.payment_evidence_id
                    ),
                    "payment_intent_id": (
                        record.payment_intent_id
                    ),
                    "evidence_source": (
                        record.evidence_source.value
                    ),
                    "external_evidence_id": (
                        record.external_evidence_id
                    ),
                    "status": (
                        record.status.value
                    ),
                }
            )

        payload = {
            "version": STORE_VERSION,
            "records": items,
        }

        self.storage_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        temporary_path = (
            self.storage_path.with_name(
                f".{self.storage_path.name}."
                f"{uuid.uuid4().hex}.tmp"
            )
        )

        try:
            with temporary_path.open(
                "w",
                encoding="utf-8",
                newline="\n",
            ) as destination:
                json.dump(
                    payload,
                    destination,
                    ensure_ascii=False,
                    indent=2,
                    sort_keys=True,
                )
                destination.write(
                    "\n"
                )
                destination.flush()
                os.fsync(
                    destination.fileno()
                )

            os.replace(
                temporary_path,
                self.storage_path,
            )
        finally:
            if temporary_path.exists():
                temporary_path.unlink()


class CustomerPaymentEvidenceService:
    """
    Receive or recover normalized payment evidence.

    Receipt means only that evidence was durably recorded.
    It does not mean the payment is authentic or settled.
    """

    def __init__(
        self,
        *,
        payment_evidence_store: CustomerPaymentEvidenceStore,
        payment_intent_store: CustomerPaymentIntentStore,
    ) -> None:
        if not isinstance(
            payment_evidence_store,
            CustomerPaymentEvidenceStore,
        ):
            raise TypeError(
                "payment_evidence_store must be "
                "CustomerPaymentEvidenceStore."
            )

        if not isinstance(
            payment_intent_store,
            CustomerPaymentIntentStore,
        ):
            raise TypeError(
                "payment_intent_store must be "
                "CustomerPaymentIntentStore."
            )

        if not payment_evidence_store.is_ready():
            raise RuntimeError(
                "Customer payment evidence store "
                "is not initialized."
            )

        if not payment_intent_store.is_ready():
            raise RuntimeError(
                "Customer payment intent store "
                "is not initialized."
            )

        self._payment_evidence_store = (
            payment_evidence_store
        )
        self._payment_intent_store = (
            payment_intent_store
        )
        self._lock = threading.RLock()

    def receive(
        self,
        *,
        evidence_request_id: str,
        authorized_payment_intent: (
            CustomerPaymentIntentResult
        ),
        evidence_source: PaymentEvidenceSource,
        external_evidence_id: str,
    ) -> CustomerPaymentEvidenceRecord:
        normalized_request_id = (
            CustomerPaymentEvidenceRecord
            ._normalize_required_string(
                evidence_request_id,
                name="evidence_request_id",
            )
        )

        if not isinstance(
            authorized_payment_intent,
            CustomerPaymentIntentResult,
        ):
            raise TypeError(
                "authorized_payment_intent must be "
                "CustomerPaymentIntentResult."
            )

        if not isinstance(
            evidence_source,
            PaymentEvidenceSource,
        ):
            raise TypeError(
                "evidence_source must be "
                "PaymentEvidenceSource."
            )

        normalized_external_id = (
            CustomerPaymentEvidenceRecord
            ._normalize_required_string(
                external_evidence_id,
                name="external_evidence_id",
            )
        )

        with self._lock:
            self._require_sources_ready()

            authoritative_intent = (
                self._payment_intent_store.get(
                    payment_intent_id=(
                        authorized_payment_intent
                        .payment_intent_id
                    )
                )
            )

            if authoritative_intent is None:
                raise ValueError(
                    "Payment intent is not authoritative."
                )

            if (
                authoritative_intent
                .payment_intent_request_id
                != authorized_payment_intent
                .payment_intent_request_id
                or authoritative_intent
                .payment_intent_id
                != authorized_payment_intent
                .payment_intent_id
                or authoritative_intent.order_id
                != authorized_payment_intent.order_id
                or authoritative_intent.payment_rail
                is not authorized_payment_intent.payment_rail
                or authoritative_intent.status
                is not authorized_payment_intent.status
            ):
                raise ValueError(
                    "Payment intent is not authoritative."
                )

            if (
                authoritative_intent.status
                is not CustomerPaymentIntentStatus.PENDING
            ):
                raise ValueError(
                    "Payment intent is not eligible "
                    "for evidence receipt."
                )

            expected_source = (
                self._source_for_rail(
                    authoritative_intent.payment_rail
                )
            )

            if evidence_source is not expected_source:
                raise ValueError(
                    "Payment evidence source does not "
                    "match payment intent rail."
                )

            existing_request = (
                self._payment_evidence_store
                .get_by_evidence_request_id(
                    evidence_request_id=(
                        normalized_request_id
                    )
                )
            )

            if existing_request is not None:
                if (
                    existing_request.payment_intent_id
                    != authoritative_intent.payment_intent_id
                    or existing_request.evidence_source
                    is not evidence_source
                    or existing_request.external_evidence_id
                    != normalized_external_id
                ):
                    raise ValueError(
                        "Customer payment evidence request "
                        "is already bound to different "
                        "evidence facts."
                    )

                return existing_request

            replay = (
                self._payment_evidence_store
                .get_by_replay_identity(
                    evidence_source=evidence_source,
                    external_evidence_id=(
                        normalized_external_id
                    ),
                )
            )

            if replay is not None:
                if (
                    replay.payment_intent_id
                    != authoritative_intent.payment_intent_id
                ):
                    raise ValueError(
                        "Payment evidence replay identity "
                        "is already bound to another "
                        "payment intent."
                    )

                return replay

            record = self._create_received_record(
                evidence_request_id=(
                    normalized_request_id
                ),
                payment_intent_id=(
                    authoritative_intent.payment_intent_id
                ),
                evidence_source=evidence_source,
                external_evidence_id=(
                    normalized_external_id
                ),
            )

            return self._payment_evidence_store.register(
                record
            )

    def get(
        self,
        *,
        payment_evidence_id: str,
    ) -> CustomerPaymentEvidenceRecord | None:
        self._require_sources_ready()

        return self._payment_evidence_store.get(
            payment_evidence_id=payment_evidence_id
        )

    def _create_received_record(
        self,
        *,
        evidence_request_id: str,
        payment_intent_id: str,
        evidence_source: PaymentEvidenceSource,
        external_evidence_id: str,
    ) -> CustomerPaymentEvidenceRecord:
        for _ in range(
            _ID_GENERATION_ATTEMPTS
        ):
            payment_evidence_id = (
                f"payment-evidence-{uuid.uuid4().hex}"
            )

            if (
                self._payment_evidence_store.get(
                    payment_evidence_id=(
                        payment_evidence_id
                    )
                )
                is not None
            ):
                continue

            return CustomerPaymentEvidenceRecord(
                evidence_request_id=evidence_request_id,
                payment_evidence_id=payment_evidence_id,
                payment_intent_id=payment_intent_id,
                evidence_source=evidence_source,
                external_evidence_id=external_evidence_id,
                status=(
                    CustomerPaymentEvidenceStatus.RECEIVED
                ),
            )

        raise RuntimeError(
            "Unable to generate unique customer "
            "payment evidence identity."
        )

    def _require_sources_ready(
        self,
    ) -> None:
        if not self._payment_evidence_store.is_ready():
            raise RuntimeError(
                "Customer payment evidence store "
                "is not initialized."
            )

        if not self._payment_intent_store.is_ready():
            raise RuntimeError(
                "Customer payment intent store "
                "is not initialized."
            )

    @staticmethod
    def _source_for_rail(
        payment_rail: PaymentRail,
    ) -> PaymentEvidenceSource:
        if payment_rail is PaymentRail.PAYPAL:
            return PaymentEvidenceSource.PAYPAL

        if (
            payment_rail
            is PaymentRail.VND_BANK_TRANSFER
        ):
            return (
                PaymentEvidenceSource
                .VND_BANK_TRANSFER
            )

        raise ValueError(
            "Unsupported payment rail."
        )
