"""
TODOBA Customer Setup Activation Service

Owns durable pre-deployment commercial setup rights.

A setup activation represents permission for one customer
to provision at most one future TODOBA deployment.

Identity model:

    activation_request_id
        -> setup_activation_id
        -> customer_id
        -> status
        -> optional bound deployment_id

Status model:

    ACTIVE
        The setup right may be used.

    SUSPENDED
        The setup right is temporarily unavailable.

    BOUND
        The setup right has been consumed by exactly one
        authoritative customer deployment.

Important distinction:

Customer setup activation is not customer deployment
entitlement.

Setup activation exists before a deployment is created.
Deployment entitlement remains the authoritative runtime
commercial truth after deployment creation.

Safety rules:
- customer_id must already exist in CustomerIdentityRegistry
- setup_activation_id is generated by TODOBA
- identical activation request retry returns the same right
- the same activation request cannot move to another customer
- one customer may own multiple setup activations
- one setup activation may bind to at most one deployment
- one deployment may bind to at most one setup activation
- bound deployment must belong to the activation customer
- SUSPENDED activations cannot be bound
- BOUND activations cannot be suspended or reactivated
- activation-request retry never implicitly reactivates a
  suspended right
- durable state is written before RAM advances

This owner deliberately does not:
- process payment-provider events
- store payment, transaction, billing, or subscription IDs
- store email, phone, password, or customer profile data
- accept or store MT5 account fingerprints
- create customer deployments
- create Trusted Agent identities
- generate deployment secrets
- issue customer access credentials
- build or deliver packages
- authorize runtime deployment entitlement
- expose an HTTP API
"""

from dataclasses import dataclass
from enum import Enum
import json
import os
from pathlib import Path
import threading
import uuid

from backend.commercial.customer_deployment_registry import (
    CustomerDeploymentRegistry,
)
from backend.commercial.customer_identity_registry import (
    CustomerIdentityRegistry,
)


STORE_VERSION = 1
_ID_GENERATION_ATTEMPTS = 128


class CustomerSetupActivationStatus(
    str,
    Enum,
):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    BOUND = "BOUND"


@dataclass(
    frozen=True,
)
class CustomerSetupActivationRecord:
    """
    Immutable durable truth for one commercial setup right.
    """

    activation_request_id: str
    setup_activation_id: str
    customer_id: str
    status: CustomerSetupActivationStatus
    deployment_id: str | None = None

    def __post_init__(
        self,
    ) -> None:
        for name in (
            "activation_request_id",
            "setup_activation_id",
            "customer_id",
        ):
            object.__setattr__(
                self,
                name,
                self._normalize_required_string(
                    getattr(
                        self,
                        name,
                    ),
                    name=name,
                ),
            )

        if not isinstance(
            self.status,
            CustomerSetupActivationStatus,
        ):
            raise TypeError(
                "status must be "
                "CustomerSetupActivationStatus."
            )

        deployment_id = self.deployment_id

        if (
            self.status
            is CustomerSetupActivationStatus.BOUND
        ):
            if deployment_id is None:
                raise ValueError(
                    "BOUND setup activation requires "
                    "deployment_id."
                )

            object.__setattr__(
                self,
                "deployment_id",
                self._normalize_required_string(
                    deployment_id,
                    name="deployment_id",
                ),
            )

            return

        if deployment_id is not None:
            raise ValueError(
                "Only BOUND setup activation may have "
                "deployment_id."
            )

    @staticmethod
    def _normalize_required_string(
        value: str,
        *,
        name: str,
    ) -> str:
        if not isinstance(
            value,
            str,
        ):
            raise TypeError(
                f"{name} must be str."
            )

        normalized = value.strip()

        if not normalized:
            raise ValueError(
                f"{name} is required."
            )

        return normalized


class CustomerSetupActivationStore:
    """
    Durable authoritative owner of commercial setup rights.

    Primary identity:
        setup_activation_id

    Idempotency identity:
        activation_request_id

    A customer may own multiple setup activations.
    A deployment may belong to at most one setup activation.
    """

    def __init__(
        self,
        storage_path: Path,
    ) -> None:
        if not isinstance(
            storage_path,
            Path,
        ):
            raise TypeError(
                "storage_path must be Path."
            )

        self.storage_path = storage_path

        self._records: dict[
            str,
            CustomerSetupActivationRecord,
        ] = {}

        self._activation_id_by_request_id: dict[
            str,
            str,
        ] = {}

        self._activation_id_by_deployment_id: dict[
            str,
            str,
        ] = {}

        self._ready = False
        self._lock = threading.RLock()

        if self.storage_path.exists():
            self._restore_from_disk()

    def initialize_empty(
        self,
    ) -> None:
        """
        Explicitly initialize a new empty setup activation
        store.

        Missing durable storage is never silently treated as
        empty authoritative commercial state.
        """

        with self._lock:
            if self._ready:
                return

            if self.storage_path.exists():
                self._restore_from_disk()
                return

            self._write_records(
                {}
            )

            self._records = {}
            self._activation_id_by_request_id = {}
            self._activation_id_by_deployment_id = {}
            self._ready = True

    def is_ready(
        self,
    ) -> bool:
        return self._ready

    def register(
        self,
        record: CustomerSetupActivationRecord,
    ) -> CustomerSetupActivationRecord:
        """
        Persist one newly granted setup activation.

        New rights must begin ACTIVE and unbound.
        Identical registration retry is idempotent.
        """

        if not isinstance(
            record,
            CustomerSetupActivationRecord,
        ):
            raise TypeError(
                "CustomerSetupActivationStore requires "
                "CustomerSetupActivationRecord."
            )

        if (
            record.status
            is not CustomerSetupActivationStatus.ACTIVE
        ):
            raise ValueError(
                "New setup activation must start ACTIVE."
            )

        if record.deployment_id is not None:
            raise ValueError(
                "New setup activation must be unbound."
            )

        with self._lock:
            self._require_ready()

            existing_request_activation_id = (
                self._activation_id_by_request_id.get(
                    record.activation_request_id
                )
            )

            if existing_request_activation_id is not None:
                existing = self._records[
                    existing_request_activation_id
                ]

                if existing != record:
                    raise ValueError(
                        "Setup activation request is "
                        "already bound to different "
                        "activation truth."
                    )

                return existing

            existing = self._records.get(
                record.setup_activation_id
            )

            if existing is not None:
                if existing != record:
                    raise ValueError(
                        "Setup activation identity is "
                        "already assigned."
                    )

                return existing

            candidate = dict(
                self._records
            )

            candidate[
                record.setup_activation_id
            ] = record

            self._write_records(
                candidate
            )

            request_index = dict(
                self._activation_id_by_request_id
            )

            request_index[
                record.activation_request_id
            ] = record.setup_activation_id

            self._records = candidate
            self._activation_id_by_request_id = (
                request_index
            )

            return record

    def get(
        self,
        *,
        setup_activation_id: str,
    ) -> CustomerSetupActivationRecord | None:
        self._require_ready()

        normalized_activation_id = (
            CustomerSetupActivationRecord
            ._normalize_required_string(
                setup_activation_id,
                name="setup_activation_id",
            )
        )

        return self._records.get(
            normalized_activation_id
        )

    def get_by_activation_request_id(
        self,
        *,
        activation_request_id: str,
    ) -> CustomerSetupActivationRecord | None:
        self._require_ready()

        normalized_request_id = (
            CustomerSetupActivationRecord
            ._normalize_required_string(
                activation_request_id,
                name="activation_request_id",
            )
        )

        activation_id = (
            self._activation_id_by_request_id.get(
                normalized_request_id
            )
        )

        if activation_id is None:
            return None

        return self._records[
            activation_id
        ]

    def get_by_deployment_id(
        self,
        *,
        deployment_id: str,
    ) -> CustomerSetupActivationRecord | None:
        self._require_ready()

        normalized_deployment_id = (
            CustomerSetupActivationRecord
            ._normalize_required_string(
                deployment_id,
                name="deployment_id",
            )
        )

        activation_id = (
            self._activation_id_by_deployment_id.get(
                normalized_deployment_id
            )
        )

        if activation_id is None:
            return None

        return self._records[
            activation_id
        ]

    def suspend(
        self,
        *,
        setup_activation_id: str,
    ) -> CustomerSetupActivationRecord:
        """
        Suspend one unbound setup activation.

        ACTIVE -> SUSPENDED
        SUSPENDED -> SUSPENDED, idempotent
        BOUND -> rejected
        """

        with self._lock:
            self._require_ready()

            existing = self._require_record(
                setup_activation_id=(
                    setup_activation_id
                )
            )

            if (
                existing.status
                is CustomerSetupActivationStatus.BOUND
            ):
                raise ValueError(
                    "BOUND setup activation cannot be "
                    "suspended."
                )

            if (
                existing.status
                is CustomerSetupActivationStatus.SUSPENDED
            ):
                return existing

            updated = CustomerSetupActivationRecord(
                activation_request_id=(
                    existing.activation_request_id
                ),
                setup_activation_id=(
                    existing.setup_activation_id
                ),
                customer_id=existing.customer_id,
                status=(
                    CustomerSetupActivationStatus.SUSPENDED
                ),
            )

            return self._replace_record(
                existing=existing,
                updated=updated,
            )

    def reactivate(
        self,
        *,
        setup_activation_id: str,
    ) -> CustomerSetupActivationRecord:
        """
        Explicitly reactivate one suspended setup right.

        SUSPENDED -> ACTIVE
        ACTIVE -> ACTIVE, idempotent
        BOUND -> rejected

        This is deliberately separate from activation-request
        retry so duplicate upstream events cannot silently
        undo a suspension.
        """

        with self._lock:
            self._require_ready()

            existing = self._require_record(
                setup_activation_id=(
                    setup_activation_id
                )
            )

            if (
                existing.status
                is CustomerSetupActivationStatus.BOUND
            ):
                raise ValueError(
                    "BOUND setup activation cannot be "
                    "reactivated."
                )

            if (
                existing.status
                is CustomerSetupActivationStatus.ACTIVE
            ):
                return existing

            updated = CustomerSetupActivationRecord(
                activation_request_id=(
                    existing.activation_request_id
                ),
                setup_activation_id=(
                    existing.setup_activation_id
                ),
                customer_id=existing.customer_id,
                status=(
                    CustomerSetupActivationStatus.ACTIVE
                ),
            )

            return self._replace_record(
                existing=existing,
                updated=updated,
            )

    def bind(
        self,
        *,
        setup_activation_id: str,
        deployment_id: str,
    ) -> CustomerSetupActivationRecord:
        """
        Permanently bind one ACTIVE setup activation to one
        deployment.

        Identical BOUND retry is idempotent.
        Binding to a different deployment fails closed.
        SUSPENDED rights cannot be bound.
        One deployment cannot consume two setup rights.
        """

        normalized_deployment_id = (
            CustomerSetupActivationRecord
            ._normalize_required_string(
                deployment_id,
                name="deployment_id",
            )
        )

        with self._lock:
            self._require_ready()

            existing = self._require_record(
                setup_activation_id=(
                    setup_activation_id
                )
            )

            if (
                existing.status
                is CustomerSetupActivationStatus.BOUND
            ):
                if (
                    existing.deployment_id
                    == normalized_deployment_id
                ):
                    return existing

                raise ValueError(
                    "Setup activation is already bound "
                    "to a different deployment."
                )

            if (
                existing.status
                is CustomerSetupActivationStatus.SUSPENDED
            ):
                raise ValueError(
                    "SUSPENDED setup activation cannot "
                    "be bound."
                )

            existing_activation_id = (
                self._activation_id_by_deployment_id.get(
                    normalized_deployment_id
                )
            )

            if existing_activation_id is not None:
                if (
                    existing_activation_id
                    == existing.setup_activation_id
                ):
                    raise RuntimeError(
                        "Setup activation deployment "
                        "index is inconsistent."
                    )

                raise ValueError(
                    "Deployment is already bound to "
                    "another setup activation."
                )

            updated = CustomerSetupActivationRecord(
                activation_request_id=(
                    existing.activation_request_id
                ),
                setup_activation_id=(
                    existing.setup_activation_id
                ),
                customer_id=existing.customer_id,
                status=(
                    CustomerSetupActivationStatus.BOUND
                ),
                deployment_id=(
                    normalized_deployment_id
                ),
            )

            return self._replace_record(
                existing=existing,
                updated=updated,
            )

    def all(
        self,
    ) -> tuple[
        CustomerSetupActivationRecord,
        ...,
    ]:
        self._require_ready()

        return tuple(
            self._records[
                activation_id
            ]
            for activation_id in sorted(
                self._records
            )
        )

    def size(
        self,
    ) -> int:
        self._require_ready()

        return len(
            self._records
        )

    def _require_record(
        self,
        *,
        setup_activation_id: str,
    ) -> CustomerSetupActivationRecord:
        normalized_activation_id = (
            CustomerSetupActivationRecord
            ._normalize_required_string(
                setup_activation_id,
                name="setup_activation_id",
            )
        )

        existing = self._records.get(
            normalized_activation_id
        )

        if existing is None:
            raise ValueError(
                "Unknown setup activation."
            )

        return existing

    def _replace_record(
        self,
        *,
        existing: CustomerSetupActivationRecord,
        updated: CustomerSetupActivationRecord,
    ) -> CustomerSetupActivationRecord:
        if (
            existing.activation_request_id
            != updated.activation_request_id
            or existing.setup_activation_id
            != updated.setup_activation_id
            or existing.customer_id
            != updated.customer_id
        ):
            raise RuntimeError(
                "Setup activation immutable identity "
                "cannot change."
            )

        candidate = dict(
            self._records
        )

        candidate[
            existing.setup_activation_id
        ] = updated

        self._write_records(
            candidate
        )

        deployment_index = dict(
            self._activation_id_by_deployment_id
        )

        if updated.deployment_id is not None:
            deployment_index[
                updated.deployment_id
            ] = updated.setup_activation_id

        self._records = candidate
        self._activation_id_by_deployment_id = (
            deployment_index
        )

        return updated

    def _require_ready(
        self,
    ) -> None:
        if not self._ready:
            raise RuntimeError(
                "Customer setup activation store is "
                "not initialized."
            )

    def _restore_from_disk(
        self,
    ) -> None:
        payload = json.loads(
            self.storage_path.read_text(
                encoding="utf-8",
            )
        )

        if not isinstance(
            payload,
            dict,
        ):
            raise ValueError(
                "Customer setup activation payload "
                "must be an object."
            )

        if set(
            payload
        ) != {
            "version",
            "records",
        }:
            raise ValueError(
                "Customer setup activation payload has "
                "invalid fields."
            )

        if payload.get(
            "version"
        ) != STORE_VERSION:
            raise ValueError(
                "Unsupported customer setup activation "
                "store version."
            )

        items = payload.get(
            "records"
        )

        if not isinstance(
            items,
            list,
        ):
            raise ValueError(
                "Customer setup activation records must "
                "be a list."
            )

        restored: dict[
            str,
            CustomerSetupActivationRecord,
        ] = {}

        request_index: dict[
            str,
            str,
        ] = {}

        deployment_index: dict[
            str,
            str,
        ] = {}

        for item in items:
            if not isinstance(
                item,
                dict,
            ):
                raise ValueError(
                    "Customer setup activation item must "
                    "be an object."
                )

            if set(
                item
            ) != {
                "activation_request_id",
                "setup_activation_id",
                "customer_id",
                "status",
                "deployment_id",
            }:
                raise ValueError(
                    "Customer setup activation item has "
                    "invalid fields."
                )

            try:
                status = CustomerSetupActivationStatus(
                    item[
                        "status"
                    ]
                )
            except (
                TypeError,
                ValueError,
            ) as exc:
                raise ValueError(
                    "Customer setup activation item has "
                    "invalid status."
                ) from exc

            record = CustomerSetupActivationRecord(
                activation_request_id=item[
                    "activation_request_id"
                ],
                setup_activation_id=item[
                    "setup_activation_id"
                ],
                customer_id=item[
                    "customer_id"
                ],
                status=status,
                deployment_id=item[
                    "deployment_id"
                ],
            )

            if (
                record.setup_activation_id
                in restored
            ):
                raise ValueError(
                    "Duplicate setup activation identity."
                )

            if (
                record.activation_request_id
                in request_index
            ):
                raise ValueError(
                    "Duplicate setup activation request."
                )

            if record.deployment_id is not None:
                if (
                    record.deployment_id
                    in deployment_index
                ):
                    raise ValueError(
                        "Deployment is bound to multiple "
                        "setup activations."
                    )

                deployment_index[
                    record.deployment_id
                ] = record.setup_activation_id

            restored[
                record.setup_activation_id
            ] = record

            request_index[
                record.activation_request_id
            ] = record.setup_activation_id

        self._records = restored
        self._activation_id_by_request_id = (
            request_index
        )
        self._activation_id_by_deployment_id = (
            deployment_index
        )
        self._ready = True

    def _write_records(
        self,
        records: dict[
            str,
            CustomerSetupActivationRecord,
        ],
    ) -> None:
        items = []

        for activation_id in sorted(
            records
        ):
            record = records[
                activation_id
            ]

            items.append(
                {
                    "activation_request_id": (
                        record.activation_request_id
                    ),
                    "setup_activation_id": (
                        record.setup_activation_id
                    ),
                    "customer_id": (
                        record.customer_id
                    ),
                    "status": (
                        record.status.value
                    ),
                    "deployment_id": (
                        record.deployment_id
                    ),
                }
            )

        payload = {
            "version": STORE_VERSION,
            "records": items,
        }

        self.storage_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        temporary_path = (
            self.storage_path.with_name(
                f"{self.storage_path.name}.tmp"
            )
        )

        try:
            with temporary_path.open(
                "w",
                encoding="utf-8",
            ) as file_handle:
                json.dump(
                    payload,
                    file_handle,
                    indent=2,
                    sort_keys=True,
                )

                file_handle.write(
                    "\n"
                )

                file_handle.flush()

                os.fsync(
                    file_handle.fileno()
                )

            os.replace(
                temporary_path,
                self.storage_path,
            )
        except Exception:
            if temporary_path.exists():
                temporary_path.unlink()

            raise


@dataclass(
    frozen=True,
)
class CustomerSetupActivationResult:
    """
    Safe result describing one setup activation.
    """

    activation_request_id: str
    setup_activation_id: str
    customer_id: str
    status: CustomerSetupActivationStatus
    deployment_id: str | None = None

    def __post_init__(
        self,
    ) -> None:
        validated = CustomerSetupActivationRecord(
            activation_request_id=(
                self.activation_request_id
            ),
            setup_activation_id=(
                self.setup_activation_id
            ),
            customer_id=self.customer_id,
            status=self.status,
            deployment_id=self.deployment_id,
        )

        object.__setattr__(
            self,
            "activation_request_id",
            validated.activation_request_id,
        )

        object.__setattr__(
            self,
            "setup_activation_id",
            validated.setup_activation_id,
        )

        object.__setattr__(
            self,
            "customer_id",
            validated.customer_id,
        )

        object.__setattr__(
            self,
            "deployment_id",
            validated.deployment_id,
        )


class CustomerSetupActivationService:
    """
    Grant, suspend, reactivate, and bind commercial setup
    rights against authoritative customer/deployment truth.
    """

    def __init__(
        self,
        *,
        activation_store: CustomerSetupActivationStore,
        customer_identity_registry: (
            CustomerIdentityRegistry
        ),
        deployment_registry: CustomerDeploymentRegistry,
    ) -> None:
        if not isinstance(
            activation_store,
            CustomerSetupActivationStore,
        ):
            raise TypeError(
                "activation_store must be "
                "CustomerSetupActivationStore."
            )

        if not isinstance(
            customer_identity_registry,
            CustomerIdentityRegistry,
        ):
            raise TypeError(
                "customer_identity_registry must be "
                "CustomerIdentityRegistry."
            )

        if not isinstance(
            deployment_registry,
            CustomerDeploymentRegistry,
        ):
            raise TypeError(
                "deployment_registry must be "
                "CustomerDeploymentRegistry."
            )

        if not activation_store.is_ready():
            raise RuntimeError(
                "Customer setup activation store is "
                "not initialized."
            )

        if not customer_identity_registry.is_ready():
            raise RuntimeError(
                "Customer identity registry is not "
                "initialized."
            )

        if not deployment_registry.is_ready():
            raise RuntimeError(
                "Customer deployment registry is not "
                "initialized."
            )

        self._activation_store = activation_store
        self._customer_identity_registry = (
            customer_identity_registry
        )
        self._deployment_registry = deployment_registry
        self._lock = threading.RLock()

        self._validate_authoritative_state()

    def activate(
        self,
        *,
        activation_request_id: str,
        customer_id: str,
    ) -> CustomerSetupActivationResult:
        """
        Grant or recover one setup activation.

        Retry semantics:
        - same request + same customer returns the same
          setup_activation_id
        - same request + different customer fails closed
        - retry returns current durable status unchanged
        - retry never implicitly reactivates SUSPENDED
        - retry never alters BOUND deployment truth
        """

        normalized_request_id = (
            CustomerSetupActivationRecord
            ._normalize_required_string(
                activation_request_id,
                name="activation_request_id",
            )
        )

        normalized_customer_id = (
            CustomerSetupActivationRecord
            ._normalize_required_string(
                customer_id,
                name="customer_id",
            )
        )

        with self._lock:
            self._require_sources_ready()

            self._require_customer(
                customer_id=normalized_customer_id
            )

            existing = (
                self._activation_store
                .get_by_activation_request_id(
                    activation_request_id=(
                        normalized_request_id
                    )
                )
            )

            if existing is not None:
                if (
                    existing.customer_id
                    != normalized_customer_id
                ):
                    raise ValueError(
                        "Setup activation request belongs "
                        "to a different customer."
                    )

                return self._build_result(
                    existing
                )

            record = self._create_active_record(
                activation_request_id=(
                    normalized_request_id
                ),
                customer_id=(
                    normalized_customer_id
                ),
            )

            return self._build_result(
                record
            )

    def suspend(
        self,
        *,
        setup_activation_id: str,
    ) -> CustomerSetupActivationResult:
        """
        Explicitly suspend one unbound setup right.
        """

        with self._lock:
            self._require_sources_ready()

            existing = self._require_activation(
                setup_activation_id=(
                    setup_activation_id
                )
            )

            self._require_customer(
                customer_id=existing.customer_id
            )

            updated = self._activation_store.suspend(
                setup_activation_id=(
                    existing.setup_activation_id
                )
            )

            return self._build_result(
                updated
            )

    def reactivate(
        self,
        *,
        setup_activation_id: str,
    ) -> CustomerSetupActivationResult:
        """
        Explicitly reactivate one suspended setup right.
        """

        with self._lock:
            self._require_sources_ready()

            existing = self._require_activation(
                setup_activation_id=(
                    setup_activation_id
                )
            )

            self._require_customer(
                customer_id=existing.customer_id
            )

            updated = self._activation_store.reactivate(
                setup_activation_id=(
                    existing.setup_activation_id
                )
            )

            return self._build_result(
                updated
            )

    def bind(
        self,
        *,
        setup_activation_id: str,
        deployment_id: str,
    ) -> CustomerSetupActivationResult:
        """
        Permanently consume one setup right for one
        authoritative deployment.

        The deployment must exist and belong to the same
        customer as the setup activation.
        """

        normalized_deployment_id = (
            CustomerSetupActivationRecord
            ._normalize_required_string(
                deployment_id,
                name="deployment_id",
            )
        )

        with self._lock:
            self._require_sources_ready()

            existing = self._require_activation(
                setup_activation_id=(
                    setup_activation_id
                )
            )

            self._require_customer(
                customer_id=existing.customer_id
            )

            deployment = self._deployment_registry.get(
                deployment_id=(
                    normalized_deployment_id
                )
            )

            if deployment is None:
                raise ValueError(
                    "Unknown customer deployment."
                )

            if (
                deployment.customer_id
                != existing.customer_id
            ):
                raise ValueError(
                    "Customer deployment belongs to a "
                    "different customer."
                )

            updated = self._activation_store.bind(
                setup_activation_id=(
                    existing.setup_activation_id
                ),
                deployment_id=(
                    deployment.deployment_id
                ),
            )

            return self._build_result(
                updated
            )

    def get(
        self,
        *,
        setup_activation_id: str,
    ) -> CustomerSetupActivationResult | None:
        self._require_sources_ready()

        record = self._activation_store.get(
            setup_activation_id=(
                setup_activation_id
            )
        )

        if record is None:
            return None

        return self._build_result(
            record
        )

    def _create_active_record(
        self,
        *,
        activation_request_id: str,
        customer_id: str,
    ) -> CustomerSetupActivationRecord:
        for _ in range(
            _ID_GENERATION_ATTEMPTS
        ):
            setup_activation_id = (
                f"setup-activation-{uuid.uuid4().hex}"
            )

            if (
                self._activation_store.get(
                    setup_activation_id=(
                        setup_activation_id
                    )
                )
                is not None
            ):
                continue

            record = CustomerSetupActivationRecord(
                activation_request_id=(
                    activation_request_id
                ),
                setup_activation_id=(
                    setup_activation_id
                ),
                customer_id=customer_id,
                status=(
                    CustomerSetupActivationStatus.ACTIVE
                ),
            )

            return self._activation_store.register(
                record
            )

        raise RuntimeError(
            "Unable to generate unique setup activation "
            "identity."
        )

    def _require_activation(
        self,
        *,
        setup_activation_id: str,
    ) -> CustomerSetupActivationRecord:
        record = self._activation_store.get(
            setup_activation_id=(
                setup_activation_id
            )
        )

        if record is None:
            raise ValueError(
                "Unknown setup activation."
            )

        return record

    def _require_customer(
        self,
        *,
        customer_id: str,
    ) -> None:
        identity = (
            self._customer_identity_registry.get(
                customer_id=customer_id
            )
        )

        if identity is None:
            raise ValueError(
                "Customer identity is not registered."
            )

    def _validate_authoritative_state(
        self,
    ) -> None:
        """
        Fail closed when restored setup-right truth refers to
        missing or cross-customer authoritative identities.
        """

        for record in (
            self._activation_store.all()
        ):
            identity = (
                self._customer_identity_registry.get(
                    customer_id=(
                        record.customer_id
                    )
                )
            )

            if identity is None:
                raise RuntimeError(
                    "Customer setup activation references "
                    "an unknown customer identity."
                )

            if (
                record.status
                is not CustomerSetupActivationStatus.BOUND
            ):
                continue

            if record.deployment_id is None:
                raise RuntimeError(
                    "BOUND customer setup activation is "
                    "missing deployment identity."
                )

            deployment = (
                self._deployment_registry.get(
                    deployment_id=(
                        record.deployment_id
                    )
                )
            )

            if deployment is None:
                raise RuntimeError(
                    "Customer setup activation references "
                    "an unknown customer deployment."
                )

            if (
                deployment.customer_id
                != record.customer_id
            ):
                raise RuntimeError(
                    "Customer setup activation deployment "
                    "ownership is inconsistent."
                )

    def _require_sources_ready(
        self,
    ) -> None:
        if not self._activation_store.is_ready():
            raise RuntimeError(
                "Customer setup activation store is "
                "not initialized."
            )

        if not self._customer_identity_registry.is_ready():
            raise RuntimeError(
                "Customer identity registry is not "
                "initialized."
            )

        if not self._deployment_registry.is_ready():
            raise RuntimeError(
                "Customer deployment registry is not "
                "initialized."
            )

    @staticmethod
    def _build_result(
        record: CustomerSetupActivationRecord,
    ) -> CustomerSetupActivationResult:
        return CustomerSetupActivationResult(
            activation_request_id=(
                record.activation_request_id
            ),
            setup_activation_id=(
                record.setup_activation_id
            ),
            customer_id=record.customer_id,
            status=record.status,
            deployment_id=record.deployment_id,
        )