"""
TODOBA Customer Payment Intent Service

Owns durable pre-verification payment intent truth.

Trust boundary:

    authoritative CustomerCommercialOrderResult
        -> payment_intent_request_id
        -> generated payment_intent_id
        -> selected payment_rail
        -> PENDING

Security rules:
- authorized order must exist exactly in CustomerCommercialOrderStore
- payment_intent_id is generated by TODOBA
- payment_intent_request_id is the idempotency identity
- identical retry returns the same payment intent
- one intent request cannot move to another order
- one intent request cannot change payment rail
- payment rail must be a typed PaymentRail enum
- durable state is written before RAM advances

This owner deliberately does not:
- verify bank or provider evidence
- process callbacks or webhooks
- store provider transaction identifiers
- mark payment PAID or SETTLED
- store payment credentials or secrets
- duplicate order amount or currency
- grant setup activation
- mutate deployment entitlement
- expose an HTTP API
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import json
import os
from pathlib import Path
import threading
import uuid

from backend.commercial.customer_commercial_order_service import (
    CustomerCommercialOrderResult,
    CustomerCommercialOrderStatus,
    CustomerCommercialOrderStore,
)


STORE_VERSION = 1
_ID_GENERATION_ATTEMPTS = 128


class PaymentRail(
    str,
    Enum,
):
    PAYPAL = "PAYPAL"
    VND_BANK_TRANSFER = "VND_BANK_TRANSFER"


class CustomerPaymentIntentStatus(
    str,
    Enum,
):
    PENDING = "PENDING"


@dataclass(
    frozen=True,
)
class CustomerPaymentIntentRecord:
    """
    Immutable durable binding for one payment intent.
    """

    payment_intent_request_id: str
    payment_intent_id: str
    order_id: str
    payment_rail: PaymentRail
    status: CustomerPaymentIntentStatus

    def __post_init__(
        self,
    ) -> None:
        for name in (
            "payment_intent_request_id",
            "payment_intent_id",
            "order_id",
        ):
            object.__setattr__(
                self,
                name,
                self._normalize_required_string(
                    getattr(
                        self,
                        name,
                    ),
                    name=name,
                ),
            )

        if not isinstance(
            self.payment_rail,
            PaymentRail,
        ):
            raise TypeError(
                "payment_rail must be PaymentRail."
            )

        if not isinstance(
            self.status,
            CustomerPaymentIntentStatus,
        ):
            raise TypeError(
                "status must be "
                "CustomerPaymentIntentStatus."
            )

        if (
            self.status
            is not CustomerPaymentIntentStatus.PENDING
        ):
            raise ValueError(
                "Unsupported customer payment "
                "intent status."
            )

    @staticmethod
    def _normalize_required_string(
        value: str,
        *,
        name: str,
    ) -> str:
        if not isinstance(
            value,
            str,
        ):
            raise TypeError(
                f"{name} must be str."
            )

        normalized = value.strip()

        if not normalized:
            raise ValueError(
                f"{name} is required."
            )

        return normalized


@dataclass(
    frozen=True,
)
class CustomerPaymentIntentResult:
    """
    Safe non-secret result for one payment intent.
    """

    payment_intent_request_id: str
    payment_intent_id: str
    order_id: str
    payment_rail: PaymentRail
    status: CustomerPaymentIntentStatus

    def __post_init__(
        self,
    ) -> None:
        validated = CustomerPaymentIntentRecord(
            payment_intent_request_id=(
                self.payment_intent_request_id
            ),
            payment_intent_id=(
                self.payment_intent_id
            ),
            order_id=self.order_id,
            payment_rail=self.payment_rail,
            status=self.status,
        )

        object.__setattr__(
            self,
            "payment_intent_request_id",
            validated.payment_intent_request_id,
        )
        object.__setattr__(
            self,
            "payment_intent_id",
            validated.payment_intent_id,
        )
        object.__setattr__(
            self,
            "order_id",
            validated.order_id,
        )
        object.__setattr__(
            self,
            "payment_rail",
            validated.payment_rail,
        )
        object.__setattr__(
            self,
            "status",
            validated.status,
        )


class CustomerPaymentIntentStore:
    """
    Durable authoritative owner of payment intent bindings.

    Primary identity:
        payment_intent_id

    Idempotency identity:
        payment_intent_request_id
    """

    def __init__(
        self,
        storage_path: Path,
    ) -> None:
        if not isinstance(
            storage_path,
            Path,
        ):
            raise TypeError(
                "storage_path must be Path."
            )

        self.storage_path = storage_path

        self._records: dict[
            str,
            CustomerPaymentIntentRecord,
        ] = {}

        self._intent_id_by_request_id: dict[
            str,
            str,
        ] = {}

        self._ready = False
        self._lock = threading.RLock()

        if self.storage_path.exists():
            self._restore_from_disk()

    def initialize_empty(
        self,
    ) -> None:
        with self._lock:
            if self._ready:
                return

            if self.storage_path.exists():
                self._restore_from_disk()
                return

            self._write_records(
                {}
            )

            self._records = {}
            self._intent_id_by_request_id = {}
            self._ready = True

    def is_ready(
        self,
    ) -> bool:
        return self._ready

    def register(
        self,
        record: CustomerPaymentIntentRecord,
    ) -> CustomerPaymentIntentRecord:
        if not isinstance(
            record,
            CustomerPaymentIntentRecord,
        ):
            raise TypeError(
                "CustomerPaymentIntentStore requires "
                "CustomerPaymentIntentRecord."
            )

        with self._lock:
            self._require_ready()

            existing_intent_id = (
                self._intent_id_by_request_id.get(
                    record.payment_intent_request_id
                )
            )

            if existing_intent_id is not None:
                existing = self._records[
                    existing_intent_id
                ]

                if existing != record:
                    raise ValueError(
                        "Customer payment intent request "
                        "is already bound to different "
                        "intent facts."
                    )

                return existing

            existing = self._records.get(
                record.payment_intent_id
            )

            if existing is not None:
                if existing != record:
                    raise ValueError(
                        "Customer payment intent ID "
                        "already exists."
                    )

                return existing

            candidate = dict(
                self._records
            )

            candidate[
                record.payment_intent_id
            ] = record

            self._write_records(
                candidate
            )

            request_index = dict(
                self._intent_id_by_request_id
            )
            request_index[
                record.payment_intent_request_id
            ] = record.payment_intent_id

            self._records = candidate
            self._intent_id_by_request_id = (
                request_index
            )

            return record

    def get(
        self,
        *,
        payment_intent_id: str,
    ) -> CustomerPaymentIntentRecord | None:
        self._require_ready()

        normalized = (
            CustomerPaymentIntentRecord
            ._normalize_required_string(
                payment_intent_id,
                name="payment_intent_id",
            )
        )

        return self._records.get(
            normalized
        )

    def get_by_payment_intent_request_id(
        self,
        *,
        payment_intent_request_id: str,
    ) -> CustomerPaymentIntentRecord | None:
        self._require_ready()

        normalized = (
            CustomerPaymentIntentRecord
            ._normalize_required_string(
                payment_intent_request_id,
                name="payment_intent_request_id",
            )
        )

        payment_intent_id = (
            self._intent_id_by_request_id.get(
                normalized
            )
        )

        if payment_intent_id is None:
            return None

        return self._records[
            payment_intent_id
        ]

    def all(
        self,
    ) -> tuple[
        CustomerPaymentIntentRecord,
        ...,
    ]:
        self._require_ready()

        return tuple(
            self._records[
                payment_intent_id
            ]
            for payment_intent_id in sorted(
                self._records
            )
        )

    def size(
        self,
    ) -> int:
        self._require_ready()

        return len(
            self._records
        )

    def _require_ready(
        self,
    ) -> None:
        if not self._ready:
            raise RuntimeError(
                "Customer payment intent store "
                "is not initialized."
            )

    def _restore_from_disk(
        self,
    ) -> None:
        try:
            payload = json.loads(
                self.storage_path.read_text(
                    encoding="utf-8",
                )
            )
        except (
            OSError,
            UnicodeError,
            json.JSONDecodeError,
        ) as exc:
            raise ValueError(
                "Customer payment intent store "
                "is unreadable."
            ) from exc

        if not isinstance(
            payload,
            dict,
        ):
            raise ValueError(
                "Customer payment intent store "
                "must contain an object."
            )

        if set(
            payload
        ) != {
            "version",
            "records",
        }:
            raise ValueError(
                "Customer payment intent store "
                "has invalid fields."
            )

        if (
            payload["version"]
            != STORE_VERSION
        ):
            raise ValueError(
                "Unsupported customer payment "
                "intent store version."
            )

        items = payload[
            "records"
        ]

        if not isinstance(
            items,
            list,
        ):
            raise ValueError(
                "Customer payment intent records "
                "must be a list."
            )

        restored: dict[
            str,
            CustomerPaymentIntentRecord,
        ] = {}

        request_index: dict[
            str,
            str,
        ] = {}

        for item in items:
            if not isinstance(
                item,
                dict,
            ):
                raise ValueError(
                    "Customer payment intent item "
                    "must be an object."
                )

            if set(
                item
            ) != {
                "payment_intent_request_id",
                "payment_intent_id",
                "order_id",
                "payment_rail",
                "status",
            }:
                raise ValueError(
                    "Customer payment intent item "
                    "has invalid fields."
                )

            try:
                record = CustomerPaymentIntentRecord(
                    payment_intent_request_id=item[
                        "payment_intent_request_id"
                    ],
                    payment_intent_id=item[
                        "payment_intent_id"
                    ],
                    order_id=item[
                        "order_id"
                    ],
                    payment_rail=PaymentRail(
                        item[
                            "payment_rail"
                        ]
                    ),
                    status=(
                        CustomerPaymentIntentStatus(
                            item[
                                "status"
                            ]
                        )
                    ),
                )
            except (
                TypeError,
                ValueError,
            ) as exc:
                raise ValueError(
                    "Customer payment intent item "
                    "is invalid."
                ) from exc

            if (
                record.payment_intent_id
                in restored
            ):
                raise ValueError(
                    "Duplicate customer payment "
                    "intent ID."
                )

            if (
                record.payment_intent_request_id
                in request_index
            ):
                raise ValueError(
                    "Duplicate customer payment "
                    "intent request."
                )

            restored[
                record.payment_intent_id
            ] = record

            request_index[
                record.payment_intent_request_id
            ] = record.payment_intent_id

        self._records = restored
        self._intent_id_by_request_id = (
            request_index
        )
        self._ready = True

    def _write_records(
        self,
        records: dict[
            str,
            CustomerPaymentIntentRecord,
        ],
    ) -> None:
        items = []

        for payment_intent_id in sorted(
            records
        ):
            record = records[
                payment_intent_id
            ]

            items.append(
                {
                    "payment_intent_request_id": (
                        record.payment_intent_request_id
                    ),
                    "payment_intent_id": (
                        record.payment_intent_id
                    ),
                    "order_id": (
                        record.order_id
                    ),
                    "payment_rail": (
                        record.payment_rail.value
                    ),
                    "status": (
                        record.status.value
                    ),
                }
            )

        payload = {
            "version": STORE_VERSION,
            "records": items,
        }

        self.storage_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        temporary_path = (
            self.storage_path.with_name(
                f".{self.storage_path.name}."
                f"{uuid.uuid4().hex}.tmp"
            )
        )

        try:
            with temporary_path.open(
                "w",
                encoding="utf-8",
                newline="\n",
            ) as destination:
                json.dump(
                    payload,
                    destination,
                    ensure_ascii=False,
                    indent=2,
                    sort_keys=True,
                )
                destination.write(
                    "\n"
                )
                destination.flush()
                os.fsync(
                    destination.fileno()
                )

            os.replace(
                temporary_path,
                self.storage_path,
            )
        finally:
            if temporary_path.exists():
                temporary_path.unlink()


class CustomerPaymentIntentService:
    """
    Create or recover one authoritative payment intent.
    """

    def __init__(
        self,
        *,
        payment_intent_store: CustomerPaymentIntentStore,
        order_store: CustomerCommercialOrderStore,
    ) -> None:
        if not isinstance(
            payment_intent_store,
            CustomerPaymentIntentStore,
        ):
            raise TypeError(
                "payment_intent_store must be "
                "CustomerPaymentIntentStore."
            )

        if not isinstance(
            order_store,
            CustomerCommercialOrderStore,
        ):
            raise TypeError(
                "order_store must be "
                "CustomerCommercialOrderStore."
            )

        if not payment_intent_store.is_ready():
            raise RuntimeError(
                "Customer payment intent store "
                "is not initialized."
            )

        if not order_store.is_ready():
            raise RuntimeError(
                "Customer commercial order store "
                "is not initialized."
            )

        self._payment_intent_store = (
            payment_intent_store
        )
        self._order_store = order_store
        self._lock = threading.RLock()

    def create(
        self,
        *,
        payment_intent_request_id: str,
        authorized_order: CustomerCommercialOrderResult,
        payment_rail: PaymentRail,
    ) -> CustomerPaymentIntentResult:
        normalized_request_id = (
            CustomerPaymentIntentRecord
            ._normalize_required_string(
                payment_intent_request_id,
                name="payment_intent_request_id",
            )
        )

        if not isinstance(
            authorized_order,
            CustomerCommercialOrderResult,
        ):
            raise TypeError(
                "authorized_order must be "
                "CustomerCommercialOrderResult."
            )

        if not isinstance(
            payment_rail,
            PaymentRail,
        ):
            raise TypeError(
                "payment_rail must be PaymentRail."
            )

        with self._lock:
            self._require_sources_ready()

            authoritative_order = (
                self._order_store.get(
                    order_id=authorized_order.order_id
                )
            )

            if authoritative_order is None:
                raise ValueError(
                    "Commercial order is not authoritative."
                )

            if (
                authoritative_order.order_request_id
                != authorized_order.order_request_id
                or authoritative_order.order_id
                != authorized_order.order_id
                or authoritative_order.customer_id
                != authorized_order.customer_id
                or authoritative_order.amount_minor
                != authorized_order.amount_minor
                or authoritative_order.currency
                != authorized_order.currency
                or authoritative_order.status
                is not authorized_order.status
            ):
                raise ValueError(
                    "Commercial order is not authoritative."
                )

            if (
                authoritative_order.status
                is not CustomerCommercialOrderStatus.PENDING
            ):
                raise ValueError(
                    "Commercial order is not eligible "
                    "for payment intent creation."
                )

            existing = (
                self._payment_intent_store
                .get_by_payment_intent_request_id(
                    payment_intent_request_id=(
                        normalized_request_id
                    )
                )
            )

            if existing is not None:
                if (
                    existing.order_id
                    != authoritative_order.order_id
                    or existing.payment_rail
                    is not payment_rail
                ):
                    raise ValueError(
                        "Customer payment intent request "
                        "is already bound to different "
                        "intent facts."
                    )

                return self._build_result(
                    existing
                )

            record = self._create_pending_record(
                payment_intent_request_id=(
                    normalized_request_id
                ),
                order_id=(
                    authoritative_order.order_id
                ),
                payment_rail=payment_rail,
            )

            stored = (
                self._payment_intent_store.register(
                    record
                )
            )

            return self._build_result(
                stored
            )

    def get(
        self,
        *,
        payment_intent_id: str,
    ) -> CustomerPaymentIntentResult | None:
        self._require_sources_ready()

        record = self._payment_intent_store.get(
            payment_intent_id=payment_intent_id
        )

        if record is None:
            return None

        return self._build_result(
            record
        )

    def _create_pending_record(
        self,
        *,
        payment_intent_request_id: str,
        order_id: str,
        payment_rail: PaymentRail,
    ) -> CustomerPaymentIntentRecord:
        for _ in range(
            _ID_GENERATION_ATTEMPTS
        ):
            payment_intent_id = (
                f"payment-intent-{uuid.uuid4().hex}"
            )

            if (
                self._payment_intent_store.get(
                    payment_intent_id=(
                        payment_intent_id
                    )
                )
                is not None
            ):
                continue

            return CustomerPaymentIntentRecord(
                payment_intent_request_id=(
                    payment_intent_request_id
                ),
                payment_intent_id=(
                    payment_intent_id
                ),
                order_id=order_id,
                payment_rail=payment_rail,
                status=(
                    CustomerPaymentIntentStatus.PENDING
                ),
            )

        raise RuntimeError(
            "Unable to generate unique customer "
            "payment intent identity."
        )

    def _require_sources_ready(
        self,
    ) -> None:
        if not self._payment_intent_store.is_ready():
            raise RuntimeError(
                "Customer payment intent store "
                "is not initialized."
            )

        if not self._order_store.is_ready():
            raise RuntimeError(
                "Customer commercial order store "
                "is not initialized."
            )

    @staticmethod
    def _build_result(
        record: CustomerPaymentIntentRecord,
    ) -> CustomerPaymentIntentResult:
        return CustomerPaymentIntentResult(
            payment_intent_request_id=(
                record.payment_intent_request_id
            ),
            payment_intent_id=(
                record.payment_intent_id
            ),
            order_id=record.order_id,
            payment_rail=record.payment_rail,
            status=record.status,
        )
