"""
TODOBA Customer Registration Service Tests

Owner contract:
- registration identity is registration_request_id
- customer_id is generated by TODOBA
- one request owns exactly one customer_id
- one generated customer_id cannot belong to two requests
- identical retry is idempotent
- durable registration is written before downstream
  CustomerIdentity registration
- retry repairs missing downstream CustomerIdentity using
  the persisted customer_id
- registration state contains no profile, payment,
  deployment, credential, secret, entitlement, or package
  material
"""

import json
from pathlib import Path
from types import SimpleNamespace

import pytest

import backend.commercial.customer_registration_service as registration_module
from backend.commercial.customer_identity_registry import (
    CustomerIdentity,
    CustomerIdentityRegistry,
)
from backend.commercial.customer_registration_service import (
    CustomerRegistrationRecord,
    CustomerRegistrationResult,
    CustomerRegistrationService,
    CustomerRegistrationStore,
)


def build_environment(
    tmp_path: Path,
) -> tuple[
    CustomerRegistrationStore,
    CustomerIdentityRegistry,
    CustomerRegistrationService,
]:
    identity_registry = CustomerIdentityRegistry(
        tmp_path
        / "customer_identities.json"
    )
    identity_registry.initialize_empty()

    registration_store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )
    registration_store.initialize_empty()

    service = CustomerRegistrationService(
        registration_store=registration_store,
        customer_identity_registry=identity_registry,
    )

    return (
        registration_store,
        identity_registry,
        service,
    )


def test_registration_record_normalizes_fields() -> None:
    record = CustomerRegistrationRecord(
        registration_request_id="  request-001  ",
        customer_id="  customer-001  ",
    )

    assert (
        record.registration_request_id
        == "request-001"
    )
    assert record.customer_id == "customer-001"


@pytest.mark.parametrize(
    ("field_name", "value"),
    [
        (
            "registration_request_id",
            None,
        ),
        (
            "customer_id",
            None,
        ),
    ],
)
def test_registration_record_requires_string_fields(
    field_name: str,
    value: object,
) -> None:
    values = {
        "registration_request_id": "request-001",
        "customer_id": "customer-001",
    }

    values[field_name] = value

    with pytest.raises(
        TypeError,
        match=f"{field_name} must be str",
    ):
        CustomerRegistrationRecord(
            **values,
        )


@pytest.mark.parametrize(
    "field_name",
    [
        "registration_request_id",
        "customer_id",
    ],
)
def test_registration_record_rejects_empty_fields(
    field_name: str,
) -> None:
    values = {
        "registration_request_id": "request-001",
        "customer_id": "customer-001",
    }

    values[field_name] = "   "

    with pytest.raises(
        ValueError,
        match=f"{field_name} is required",
    ):
        CustomerRegistrationRecord(
            **values,
        )


def test_registration_result_normalizes_fields() -> None:
    result = CustomerRegistrationResult(
        registration_request_id="  request-001  ",
        customer_id="  customer-001  ",
    )

    assert (
        result.registration_request_id
        == "request-001"
    )
    assert result.customer_id == "customer-001"


def test_store_requires_path() -> None:
    with pytest.raises(
        TypeError,
        match="storage_path must be Path",
    ):
        CustomerRegistrationStore(
            "customer_registrations.json",
        )


def test_store_requires_explicit_initialization(
    tmp_path: Path,
) -> None:
    store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )

    assert not store.is_ready()

    with pytest.raises(
        RuntimeError,
        match="Customer registration store is not initialized",
    ):
        store.size()


def test_initialize_empty_creates_durable_store(
    tmp_path: Path,
) -> None:
    storage_path = (
        tmp_path
        / "nested"
        / "customer_registrations.json"
    )

    store = CustomerRegistrationStore(
        storage_path
    )

    assert not storage_path.exists()

    store.initialize_empty()

    assert store.is_ready()
    assert store.size() == 0
    assert storage_path.exists()

    payload = json.loads(
        storage_path.read_text(
            encoding="utf-8",
        )
    )

    assert payload == {
        "records": [],
        "version": 1,
    }


def test_store_registers_first_record(
    tmp_path: Path,
) -> None:
    store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )
    store.initialize_empty()

    record = CustomerRegistrationRecord(
        registration_request_id="request-001",
        customer_id="customer-001",
    )

    result = store.register(
        record
    )

    assert result == record
    assert store.size() == 1
    assert (
        store.get(
            registration_request_id="request-001"
        )
        == record
    )
    assert (
        store.get_by_customer_id(
            customer_id="customer-001"
        )
        == record
    )


def test_identical_store_registration_is_idempotent(
    tmp_path: Path,
) -> None:
    store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )
    store.initialize_empty()

    first = CustomerRegistrationRecord(
        registration_request_id="request-001",
        customer_id="customer-001",
    )

    second = CustomerRegistrationRecord(
        registration_request_id="request-001",
        customer_id="customer-001",
    )

    assert store.register(first) == first
    assert store.register(second) == first
    assert store.size() == 1


def test_store_rejects_conflicting_request_reuse(
    tmp_path: Path,
) -> None:
    store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )
    store.initialize_empty()

    store.register(
        CustomerRegistrationRecord(
            registration_request_id="request-001",
            customer_id="customer-001",
        )
    )

    with pytest.raises(
        ValueError,
        match=(
            "Customer registration request is already "
            "bound to a different customer identity"
        ),
    ):
        store.register(
            CustomerRegistrationRecord(
                registration_request_id="request-001",
                customer_id="customer-002",
            )
        )

    assert store.size() == 1


def test_store_rejects_customer_reuse_across_requests(
    tmp_path: Path,
) -> None:
    store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )
    store.initialize_empty()

    store.register(
        CustomerRegistrationRecord(
            registration_request_id="request-001",
            customer_id="customer-001",
        )
    )

    with pytest.raises(
        ValueError,
        match=(
            "Customer identity is already bound to "
            "another registration request"
        ),
    ):
        store.register(
            CustomerRegistrationRecord(
                registration_request_id="request-002",
                customer_id="customer-001",
            )
        )

    assert store.size() == 1


def test_store_lookup_normalizes_identity(
    tmp_path: Path,
) -> None:
    store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )
    store.initialize_empty()

    record = store.register(
        CustomerRegistrationRecord(
            registration_request_id="request-001",
            customer_id="customer-001",
        )
    )

    assert (
        store.get(
            registration_request_id="  request-001  "
        )
        == record
    )

    assert (
        store.get_by_customer_id(
            customer_id="  customer-001  "
        )
        == record
    )


def test_store_all_is_deterministic(
    tmp_path: Path,
) -> None:
    store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )
    store.initialize_empty()

    store.register(
        CustomerRegistrationRecord(
            registration_request_id="request-b",
            customer_id="customer-b",
        )
    )

    store.register(
        CustomerRegistrationRecord(
            registration_request_id="request-a",
            customer_id="customer-a",
        )
    )

    assert tuple(
        record.registration_request_id
        for record in store.all()
    ) == (
        "request-a",
        "request-b",
    )


def test_store_restores_durable_state(
    tmp_path: Path,
) -> None:
    storage_path = (
        tmp_path
        / "customer_registrations.json"
    )

    first = CustomerRegistrationStore(
        storage_path
    )
    first.initialize_empty()

    record = first.register(
        CustomerRegistrationRecord(
            registration_request_id="request-001",
            customer_id="customer-001",
        )
    )

    restarted = CustomerRegistrationStore(
        storage_path
    )

    assert restarted.is_ready()
    assert restarted.size() == 1

    assert (
        restarted.get(
            registration_request_id="request-001"
        )
        == record
    )

    assert (
        restarted.get_by_customer_id(
            customer_id="customer-001"
        )
        == record
    )


@pytest.mark.parametrize(
    "payload",
    [
        [],
        {
            "version": 999,
            "records": [],
        },
        {
            "version": 1,
            "records": "invalid",
        },
        {
            "version": 1,
            "records": [],
            "unexpected": True,
        },
        {
            "version": 1,
            "records": [
                "invalid",
            ],
        },
        {
            "version": 1,
            "records": [
                {
                    "registration_request_id": "request-001",
                    "customer_id": "customer-001",
                    "unexpected": True,
                }
            ],
        },
    ],
)
def test_store_rejects_malformed_durable_payload(
    tmp_path: Path,
    payload: object,
) -> None:
    storage_path = (
        tmp_path
        / "customer_registrations.json"
    )

    storage_path.write_text(
        json.dumps(
            payload
        ),
        encoding="utf-8",
    )

    with pytest.raises(
        (
            TypeError,
            ValueError,
        )
    ):
        CustomerRegistrationStore(
            storage_path
        )


def test_restore_rejects_duplicate_request(
    tmp_path: Path,
) -> None:
    storage_path = (
        tmp_path
        / "customer_registrations.json"
    )

    storage_path.write_text(
        json.dumps(
            {
                "version": 1,
                "records": [
                    {
                        "registration_request_id": "request-001",
                        "customer_id": "customer-001",
                    },
                    {
                        "registration_request_id": "request-001",
                        "customer_id": "customer-002",
                    },
                ],
            }
        ),
        encoding="utf-8",
    )

    with pytest.raises(
        ValueError,
        match="Duplicate customer registration request",
    ):
        CustomerRegistrationStore(
            storage_path
        )


def test_restore_rejects_duplicate_customer(
    tmp_path: Path,
) -> None:
    storage_path = (
        tmp_path
        / "customer_registrations.json"
    )

    storage_path.write_text(
        json.dumps(
            {
                "version": 1,
                "records": [
                    {
                        "registration_request_id": "request-001",
                        "customer_id": "customer-001",
                    },
                    {
                        "registration_request_id": "request-002",
                        "customer_id": "customer-001",
                    },
                ],
            }
        ),
        encoding="utf-8",
    )

    with pytest.raises(
        ValueError,
        match=(
            "Customer identity is bound to multiple "
            "registration requests"
        ),
    ):
        CustomerRegistrationStore(
            storage_path
        )


def test_service_requires_registration_store(
    tmp_path: Path,
) -> None:
    identity_registry = CustomerIdentityRegistry(
        tmp_path
        / "customer_identities.json"
    )
    identity_registry.initialize_empty()

    with pytest.raises(
        TypeError,
        match="registration_store",
    ):
        CustomerRegistrationService(
            registration_store=object(),
            customer_identity_registry=identity_registry,
        )


def test_service_requires_customer_identity_registry(
    tmp_path: Path,
) -> None:
    registration_store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )
    registration_store.initialize_empty()

    with pytest.raises(
        TypeError,
        match="customer_identity_registry",
    ):
        CustomerRegistrationService(
            registration_store=registration_store,
            customer_identity_registry=object(),
        )


def test_service_requires_ready_registration_store(
    tmp_path: Path,
) -> None:
    registration_store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )

    identity_registry = CustomerIdentityRegistry(
        tmp_path
        / "customer_identities.json"
    )
    identity_registry.initialize_empty()

    with pytest.raises(
        RuntimeError,
        match="Customer registration store is not initialized",
    ):
        CustomerRegistrationService(
            registration_store=registration_store,
            customer_identity_registry=identity_registry,
        )


def test_service_requires_ready_identity_registry(
    tmp_path: Path,
) -> None:
    registration_store = CustomerRegistrationStore(
        tmp_path
        / "customer_registrations.json"
    )
    registration_store.initialize_empty()

    identity_registry = CustomerIdentityRegistry(
        tmp_path
        / "customer_identities.json"
    )

    with pytest.raises(
        RuntimeError,
        match="Customer identity registry is not initialized",
    ):
        CustomerRegistrationService(
            registration_store=registration_store,
            customer_identity_registry=identity_registry,
        )


def test_service_registers_new_customer(
    tmp_path: Path,
) -> None:
    (
        registration_store,
        identity_registry,
        service,
    ) = build_environment(
        tmp_path
    )

    result = service.register(
        registration_request_id="registration-001"
    )

    assert (
        result.registration_request_id
        == "registration-001"
    )

    assert result.customer_id.startswith(
        "customer-"
    )

    assert len(
        result.customer_id
    ) > len(
        "customer-"
    )

    assert registration_store.size() == 1
    assert identity_registry.size() == 1

    stored = registration_store.get(
        registration_request_id="registration-001"
    )

    assert stored is not None
    assert (
        stored.customer_id
        == result.customer_id
    )

    identity = identity_registry.get(
        customer_id=result.customer_id
    )

    assert identity is not None
    assert (
        identity.customer_id
        == result.customer_id
    )


def test_service_normalizes_registration_request(
    tmp_path: Path,
) -> None:
    (
        registration_store,
        _,
        service,
    ) = build_environment(
        tmp_path
    )

    result = service.register(
        registration_request_id=(
            "  registration-001  "
        )
    )

    assert (
        result.registration_request_id
        == "registration-001"
    )

    stored = registration_store.get(
        registration_request_id=(
            "registration-001"
        )
    )

    assert stored is not None


@pytest.mark.parametrize(
    "value",
    [
        None,
        123,
        "",
        "   ",
    ],
)
def test_service_rejects_invalid_registration_request(
    tmp_path: Path,
    value: object,
) -> None:
    _, _, service = build_environment(
        tmp_path
    )

    with pytest.raises(
        (
            TypeError,
            ValueError,
        )
    ):
        service.register(
            registration_request_id=value,
        )


def test_service_retry_returns_same_customer(
    tmp_path: Path,
) -> None:
    (
        registration_store,
        identity_registry,
        service,
    ) = build_environment(
        tmp_path
    )

    first = service.register(
        registration_request_id="registration-001"
    )

    second = service.register(
        registration_request_id="registration-001"
    )

    assert second == first
    assert registration_store.size() == 1
    assert identity_registry.size() == 1


def test_service_persists_registration_before_identity_mutation(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    (
        registration_store,
        identity_registry,
        service,
    ) = build_environment(
        tmp_path
    )

    original_register = (
        identity_registry.register
    )

    def fail_identity_registration(
        identity: CustomerIdentity,
    ) -> CustomerIdentity:
        raise RuntimeError(
            "simulated identity registration failure"
        )

    monkeypatch.setattr(
        identity_registry,
        "register",
        fail_identity_registration,
    )

    with pytest.raises(
        RuntimeError,
        match="simulated identity registration failure",
    ):
        service.register(
            registration_request_id="registration-001"
        )

    assert registration_store.size() == 1
    assert identity_registry.size() == 0

    persisted = registration_store.get(
        registration_request_id="registration-001"
    )

    assert persisted is not None

    customer_id = persisted.customer_id

    monkeypatch.setattr(
        identity_registry,
        "register",
        original_register,
    )

    recovered = service.register(
        registration_request_id="registration-001"
    )

    assert (
        recovered.customer_id
        == customer_id
    )
    assert registration_store.size() == 1
    assert identity_registry.size() == 1


def test_service_recovers_after_process_restart(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    registration_path = (
        tmp_path
        / "customer_registrations.json"
    )

    identity_path = (
        tmp_path
        / "customer_identities.json"
    )

    identity_registry = CustomerIdentityRegistry(
        identity_path
    )
    identity_registry.initialize_empty()

    registration_store = CustomerRegistrationStore(
        registration_path
    )
    registration_store.initialize_empty()

    service = CustomerRegistrationService(
        registration_store=registration_store,
        customer_identity_registry=identity_registry,
    )

    def fail_identity_registration(
        identity: CustomerIdentity,
    ) -> CustomerIdentity:
        raise RuntimeError(
            "simulated process interruption"
        )

    monkeypatch.setattr(
        identity_registry,
        "register",
        fail_identity_registration,
    )

    with pytest.raises(
        RuntimeError,
        match="simulated process interruption",
    ):
        service.register(
            registration_request_id="registration-001"
        )

    persisted = registration_store.get(
        registration_request_id="registration-001"
    )

    assert persisted is not None
    persisted_customer_id = (
        persisted.customer_id
    )

    restarted_store = CustomerRegistrationStore(
        registration_path
    )

    restarted_identity_registry = (
        CustomerIdentityRegistry(
            identity_path
        )
    )

    restarted_service = CustomerRegistrationService(
        registration_store=restarted_store,
        customer_identity_registry=(
            restarted_identity_registry
        ),
    )

    recovered = restarted_service.register(
        registration_request_id="registration-001"
    )

    assert (
        recovered.customer_id
        == persisted_customer_id
    )
    assert restarted_store.size() == 1
    assert restarted_identity_registry.size() == 1


def test_service_avoids_existing_customer_identity_collision(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    (
        registration_store,
        identity_registry,
        service,
    ) = build_environment(
        tmp_path
    )

    identity_registry.register(
        CustomerIdentity(
            customer_id="customer-collision"
        )
    )

    generated = iter(
        [
            SimpleNamespace(
                hex="collision"
            ),
            SimpleNamespace(
                hex="fresh"
            ),
        ]
    )

    monkeypatch.setattr(
        registration_module.uuid,
        "uuid4",
        lambda: next(
            generated
        ),
    )

    result = service.register(
        registration_request_id="registration-001"
    )

    assert (
        result.customer_id
        == "customer-fresh"
    )

    assert registration_store.size() == 1
    assert identity_registry.size() == 2


def test_service_fails_when_unique_identity_cannot_be_generated(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _, identity_registry, service = build_environment(
        tmp_path
    )

    identity_registry.register(
        CustomerIdentity(
            customer_id="customer-collision"
        )
    )

    monkeypatch.setattr(
        registration_module.uuid,
        "uuid4",
        lambda: SimpleNamespace(
            hex="collision"
        ),
    )

    with pytest.raises(
        RuntimeError,
        match=(
            "Unable to generate unique customer identity"
        ),
    ):
        service.register(
            registration_request_id="registration-001"
        )


def test_registration_persistence_contains_only_owned_fields(
    tmp_path: Path,
) -> None:
    (
        registration_store,
        _,
        service,
    ) = build_environment(
        tmp_path
    )

    service.register(
        registration_request_id="registration-001"
    )

    payload = json.loads(
        registration_store.storage_path.read_text(
            encoding="utf-8",
        )
    )

    assert set(
        payload
    ) == {
        "version",
        "records",
    }

    assert len(
        payload["records"]
    ) == 1

    record = payload[
        "records"
    ][0]

    assert set(
        record
    ) == {
        "registration_request_id",
        "customer_id",
    }

    forbidden_fields = {
        "email",
        "phone",
        "password",
        "profile",
        "payment_id",
        "subscription_id",
        "deployment_id",
        "agent_id",
        "account_fingerprint",
        "credential_id",
        "access_credential",
        "secret",
        "entitlement",
        "package_path",
        "package_root",
    }

    assert forbidden_fields.isdisjoint(
        record
    )


def test_service_does_not_accept_commercial_downstream_inputs() -> None:
    import inspect

    parameters = inspect.signature(
        CustomerRegistrationService.register
    ).parameters

    assert set(
        parameters
    ) == {
        "self",
        "registration_request_id",
    }

    forbidden_parameters = {
        "customer_id",
        "email",
        "phone",
        "password",
        "payment_id",
        "subscription_id",
        "deployment_id",
        "agent_id",
        "account_fingerprint",
        "credential",
        "entitlement",
        "package",
    }

    assert forbidden_parameters.isdisjoint(
        parameters
    )