"""
TODOBA Customer Setup Activation Service Tests

Owner contract:
- one activation request creates one setup right
- setup_activation_id is generated by TODOBA
- one customer may own multiple setup rights
- one setup right may bind to at most one deployment
- one deployment may consume at most one setup right
- activation retry is idempotent
- activation retry never implicitly reactivates SUSPENDED
- activation retry never changes BOUND deployment truth
- cross-customer request reuse fails closed
- cross-customer deployment binding fails closed
- BOUND is terminal for setup-right ownership
- restored orphaned/cross-customer truth fails closed
- durable state advances before RAM state
- setup-right persistence contains no payment, account,
  credential, secret, package, or runtime entitlement data
"""

import inspect
import json
from pathlib import Path
from types import SimpleNamespace

import pytest

import backend.commercial.customer_setup_activation_service as activation_module
from backend.commercial.customer_deployment_registry import (
    CustomerDeployment,
    CustomerDeploymentRegistry,
)
from backend.commercial.customer_identity_registry import (
    CustomerIdentity,
    CustomerIdentityRegistry,
)
from backend.commercial.customer_setup_activation_service import (
    CustomerSetupActivationRecord,
    CustomerSetupActivationResult,
    CustomerSetupActivationService,
    CustomerSetupActivationStatus,
    CustomerSetupActivationStore,
)


def build_environment(
    tmp_path: Path,
) -> tuple[
    CustomerIdentityRegistry,
    CustomerDeploymentRegistry,
    CustomerSetupActivationStore,
    CustomerSetupActivationService,
]:
    identity_registry = CustomerIdentityRegistry(
        tmp_path
        / "customer_identities.json"
    )
    identity_registry.initialize_empty()

    deployment_registry = CustomerDeploymentRegistry(
        tmp_path
        / "customer_deployments.json"
    )
    deployment_registry.initialize_empty()

    activation_store = CustomerSetupActivationStore(
        tmp_path
        / "customer_setup_activations.json"
    )
    activation_store.initialize_empty()

    service = CustomerSetupActivationService(
        activation_store=activation_store,
        customer_identity_registry=identity_registry,
        deployment_registry=deployment_registry,
    )

    return (
        identity_registry,
        deployment_registry,
        activation_store,
        service,
    )


def register_customer(
    identity_registry: CustomerIdentityRegistry,
    customer_id: str = "customer-001",
) -> CustomerIdentity:
    return identity_registry.register(
        CustomerIdentity(
            customer_id=customer_id
        )
    )


def register_deployment(
    deployment_registry: CustomerDeploymentRegistry,
    *,
    customer_id: str = "customer-001",
    deployment_id: str = "deployment-001",
    agent_id: str = "trusted-agent-001",
) -> CustomerDeployment:
    return deployment_registry.register(
        CustomerDeployment(
            customer_id=customer_id,
            deployment_id=deployment_id,
            agent_id=agent_id,
        )
    )


def test_status_values_are_locked() -> None:
    assert (
        CustomerSetupActivationStatus.ACTIVE.value
        == "ACTIVE"
    )
    assert (
        CustomerSetupActivationStatus.SUSPENDED.value
        == "SUSPENDED"
    )
    assert (
        CustomerSetupActivationStatus.BOUND.value
        == "BOUND"
    )


def test_active_record_normalizes_identity_fields() -> None:
    record = CustomerSetupActivationRecord(
        activation_request_id="  request-001  ",
        setup_activation_id=(
            "  setup-activation-001  "
        ),
        customer_id="  customer-001  ",
        status=(
            CustomerSetupActivationStatus.ACTIVE
        ),
    )

    assert (
        record.activation_request_id
        == "request-001"
    )
    assert (
        record.setup_activation_id
        == "setup-activation-001"
    )
    assert record.customer_id == "customer-001"
    assert record.deployment_id is None


@pytest.mark.parametrize(
    "field_name",
    [
        "activation_request_id",
        "setup_activation_id",
        "customer_id",
    ],
)
def test_record_rejects_empty_identity(
    field_name: str,
) -> None:
    values = {
        "activation_request_id": "request-001",
        "setup_activation_id": (
            "setup-activation-001"
        ),
        "customer_id": "customer-001",
        "status": (
            CustomerSetupActivationStatus.ACTIVE
        ),
    }

    values[field_name] = "   "

    with pytest.raises(
        ValueError,
        match=f"{field_name} is required",
    ):
        CustomerSetupActivationRecord(
            **values,
        )


@pytest.mark.parametrize(
    "field_name",
    [
        "activation_request_id",
        "setup_activation_id",
        "customer_id",
    ],
)
def test_record_requires_string_identity(
    field_name: str,
) -> None:
    values = {
        "activation_request_id": "request-001",
        "setup_activation_id": (
            "setup-activation-001"
        ),
        "customer_id": "customer-001",
        "status": (
            CustomerSetupActivationStatus.ACTIVE
        ),
    }

    values[field_name] = None

    with pytest.raises(
        TypeError,
        match=f"{field_name} must be str",
    ):
        CustomerSetupActivationRecord(
            **values,
        )


def test_record_requires_status_enum() -> None:
    with pytest.raises(
        TypeError,
        match="CustomerSetupActivationStatus",
    ):
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status="ACTIVE",
        )


@pytest.mark.parametrize(
    "status",
    [
        CustomerSetupActivationStatus.ACTIVE,
        CustomerSetupActivationStatus.SUSPENDED,
    ],
)
def test_unbound_status_rejects_deployment_id(
    status: CustomerSetupActivationStatus,
) -> None:
    with pytest.raises(
        ValueError,
        match=(
            "Only BOUND setup activation may have "
            "deployment_id"
        ),
    ):
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=status,
            deployment_id="deployment-001",
        )


def test_bound_record_requires_deployment_id() -> None:
    with pytest.raises(
        ValueError,
        match=(
            "BOUND setup activation requires "
            "deployment_id"
        ),
    ):
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.BOUND
            ),
        )


def test_bound_record_normalizes_deployment_id() -> None:
    record = CustomerSetupActivationRecord(
        activation_request_id="request-001",
        setup_activation_id=(
            "setup-activation-001"
        ),
        customer_id="customer-001",
        status=(
            CustomerSetupActivationStatus.BOUND
        ),
        deployment_id="  deployment-001  ",
    )

    assert record.deployment_id == "deployment-001"


def test_result_uses_same_record_contract() -> None:
    result = CustomerSetupActivationResult(
        activation_request_id=" request-001 ",
        setup_activation_id=(
            " setup-activation-001 "
        ),
        customer_id=" customer-001 ",
        status=(
            CustomerSetupActivationStatus.ACTIVE
        ),
    )

    assert (
        result.activation_request_id
        == "request-001"
    )
    assert (
        result.setup_activation_id
        == "setup-activation-001"
    )
    assert result.customer_id == "customer-001"
    assert result.deployment_id is None


def test_store_requires_path() -> None:
    with pytest.raises(
        TypeError,
        match="storage_path must be Path",
    ):
        CustomerSetupActivationStore(
            "activations.json",
        )


def test_store_requires_explicit_initialization(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )

    assert not store.is_ready()

    with pytest.raises(
        RuntimeError,
        match=(
            "Customer setup activation store is not "
            "initialized"
        ),
    ):
        store.size()


def test_initialize_empty_creates_durable_store(
    tmp_path: Path,
) -> None:
    path = (
        tmp_path
        / "nested"
        / "activations.json"
    )

    store = CustomerSetupActivationStore(
        path
    )

    store.initialize_empty()

    assert store.is_ready()
    assert store.size() == 0

    payload = json.loads(
        path.read_text(
            encoding="utf-8",
        )
    )

    assert payload == {
        "records": [],
        "version": 1,
    }


def test_store_registers_active_right(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    record = CustomerSetupActivationRecord(
        activation_request_id="request-001",
        setup_activation_id=(
            "setup-activation-001"
        ),
        customer_id="customer-001",
        status=(
            CustomerSetupActivationStatus.ACTIVE
        ),
    )

    assert store.register(record) == record
    assert store.size() == 1

    assert (
        store.get(
            setup_activation_id=(
                "setup-activation-001"
            )
        )
        == record
    )

    assert (
        store.get_by_activation_request_id(
            activation_request_id="request-001"
        )
        == record
    )


def test_store_identical_registration_is_idempotent(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    first = CustomerSetupActivationRecord(
        activation_request_id="request-001",
        setup_activation_id=(
            "setup-activation-001"
        ),
        customer_id="customer-001",
        status=(
            CustomerSetupActivationStatus.ACTIVE
        ),
    )

    second = CustomerSetupActivationRecord(
        activation_request_id="request-001",
        setup_activation_id=(
            "setup-activation-001"
        ),
        customer_id="customer-001",
        status=(
            CustomerSetupActivationStatus.ACTIVE
        ),
    )

    assert store.register(first) == first
    assert store.register(second) == first
    assert store.size() == 1


def test_store_rejects_request_reuse_for_different_truth(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    store.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    with pytest.raises(
        ValueError,
        match=(
            "Setup activation request is already bound "
            "to different activation truth"
        ),
    ):
        store.register(
            CustomerSetupActivationRecord(
                activation_request_id="request-001",
                setup_activation_id=(
                    "setup-activation-002"
                ),
                customer_id="customer-001",
                status=(
                    CustomerSetupActivationStatus.ACTIVE
                ),
            )
        )


def test_store_rejects_activation_id_reuse(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    store.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    with pytest.raises(
        ValueError,
        match=(
            "Setup activation identity is already "
            "assigned"
        ),
    ):
        store.register(
            CustomerSetupActivationRecord(
                activation_request_id="request-002",
                setup_activation_id=(
                    "setup-activation-001"
                ),
                customer_id="customer-001",
                status=(
                    CustomerSetupActivationStatus.ACTIVE
                ),
            )
        )


@pytest.mark.parametrize(
    "status",
    [
        CustomerSetupActivationStatus.SUSPENDED,
        CustomerSetupActivationStatus.BOUND,
    ],
)
def test_store_new_registration_must_start_active(
    tmp_path: Path,
    status: CustomerSetupActivationStatus,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    deployment_id = (
        "deployment-001"
        if status
        is CustomerSetupActivationStatus.BOUND
        else None
    )

    record = CustomerSetupActivationRecord(
        activation_request_id="request-001",
        setup_activation_id=(
            "setup-activation-001"
        ),
        customer_id="customer-001",
        status=status,
        deployment_id=deployment_id,
    )

    with pytest.raises(
        ValueError,
        match="must start ACTIVE",
    ):
        store.register(
            record
        )


def test_store_suspend_and_reactivate_are_idempotent(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    record = store.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    suspended = store.suspend(
        setup_activation_id=(
            record.setup_activation_id
        )
    )

    assert (
        suspended.status
        is CustomerSetupActivationStatus.SUSPENDED
    )

    assert (
        store.suspend(
            setup_activation_id=(
                record.setup_activation_id
            )
        )
        == suspended
    )

    active = store.reactivate(
        setup_activation_id=(
            record.setup_activation_id
        )
    )

    assert (
        active.status
        is CustomerSetupActivationStatus.ACTIVE
    )

    assert (
        store.reactivate(
            setup_activation_id=(
                record.setup_activation_id
            )
        )
        == active
    )


def test_store_bind_is_terminal_and_idempotent(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    record = store.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    bound = store.bind(
        setup_activation_id=(
            record.setup_activation_id
        ),
        deployment_id="deployment-001",
    )

    assert (
        bound.status
        is CustomerSetupActivationStatus.BOUND
    )
    assert bound.deployment_id == "deployment-001"

    assert (
        store.bind(
            setup_activation_id=(
                record.setup_activation_id
            ),
            deployment_id="deployment-001",
        )
        == bound
    )

    assert (
        store.get_by_deployment_id(
            deployment_id="deployment-001"
        )
        == bound
    )


def test_store_rejects_binding_bound_right_to_other_deployment(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    record = store.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    store.bind(
        setup_activation_id=(
            record.setup_activation_id
        ),
        deployment_id="deployment-001",
    )

    with pytest.raises(
        ValueError,
        match="different deployment",
    ):
        store.bind(
            setup_activation_id=(
                record.setup_activation_id
            ),
            deployment_id="deployment-002",
        )


def test_store_rejects_two_rights_for_one_deployment(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    first = store.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    second = store.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-002",
            setup_activation_id=(
                "setup-activation-002"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    store.bind(
        setup_activation_id=(
            first.setup_activation_id
        ),
        deployment_id="deployment-001",
    )

    with pytest.raises(
        ValueError,
        match=(
            "Deployment is already bound to another "
            "setup activation"
        ),
    ):
        store.bind(
            setup_activation_id=(
                second.setup_activation_id
            ),
            deployment_id="deployment-001",
        )


def test_store_suspended_right_cannot_bind(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    record = store.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    store.suspend(
        setup_activation_id=(
            record.setup_activation_id
        )
    )

    with pytest.raises(
        ValueError,
        match="SUSPENDED setup activation cannot be bound",
    ):
        store.bind(
            setup_activation_id=(
                record.setup_activation_id
            ),
            deployment_id="deployment-001",
        )


def test_bound_right_cannot_suspend_or_reactivate(
    tmp_path: Path,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    record = store.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    store.bind(
        setup_activation_id=(
            record.setup_activation_id
        ),
        deployment_id="deployment-001",
    )

    with pytest.raises(
        ValueError,
        match="BOUND setup activation cannot be suspended",
    ):
        store.suspend(
            setup_activation_id=(
                record.setup_activation_id
            )
        )

    with pytest.raises(
        ValueError,
        match="BOUND setup activation cannot be reactivated",
    ):
        store.reactivate(
            setup_activation_id=(
                record.setup_activation_id
            )
        )


def test_store_write_failure_does_not_advance_ram(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    store.initialize_empty()

    record = CustomerSetupActivationRecord(
        activation_request_id="request-001",
        setup_activation_id=(
            "setup-activation-001"
        ),
        customer_id="customer-001",
        status=(
            CustomerSetupActivationStatus.ACTIVE
        ),
    )

    def fail_write(
        records: object,
    ) -> None:
        raise RuntimeError(
            "simulated activation write failure"
        )

    monkeypatch.setattr(
        store,
        "_write_records",
        fail_write,
    )

    with pytest.raises(
        RuntimeError,
        match="simulated activation write failure",
    ):
        store.register(
            record
        )

    assert store.size() == 0
    assert (
        store.get(
            setup_activation_id=(
                "setup-activation-001"
            )
        )
        is None
    )


def test_store_restores_all_indexes(
    tmp_path: Path,
) -> None:
    path = (
        tmp_path
        / "activations.json"
    )

    first = CustomerSetupActivationStore(
        path
    )
    first.initialize_empty()

    record = first.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    bound = first.bind(
        setup_activation_id=(
            record.setup_activation_id
        ),
        deployment_id="deployment-001",
    )

    restarted = CustomerSetupActivationStore(
        path
    )

    assert restarted.is_ready()
    assert restarted.size() == 1

    assert (
        restarted.get(
            setup_activation_id=(
                bound.setup_activation_id
            )
        )
        == bound
    )

    assert (
        restarted.get_by_activation_request_id(
            activation_request_id="request-001"
        )
        == bound
    )

    assert (
        restarted.get_by_deployment_id(
            deployment_id="deployment-001"
        )
        == bound
    )


@pytest.mark.parametrize(
    "payload",
    [
        [],
        {
            "version": 999,
            "records": [],
        },
        {
            "version": 1,
            "records": "invalid",
        },
        {
            "version": 1,
            "records": [],
            "unexpected": True,
        },
        {
            "version": 1,
            "records": [
                "invalid",
            ],
        },
        {
            "version": 1,
            "records": [
                {
                    "activation_request_id": (
                        "request-001"
                    ),
                    "setup_activation_id": (
                        "setup-activation-001"
                    ),
                    "customer_id": "customer-001",
                    "status": "INVALID",
                    "deployment_id": None,
                }
            ],
        },
    ],
)
def test_store_rejects_malformed_payload(
    tmp_path: Path,
    payload: object,
) -> None:
    path = (
        tmp_path
        / "activations.json"
    )

    path.write_text(
        json.dumps(
            payload
        ),
        encoding="utf-8",
    )

    with pytest.raises(
        (
            TypeError,
            ValueError,
        )
    ):
        CustomerSetupActivationStore(
            path
        )


def test_restore_rejects_duplicate_request(
    tmp_path: Path,
) -> None:
    path = (
        tmp_path
        / "activations.json"
    )

    path.write_text(
        json.dumps(
            {
                "version": 1,
                "records": [
                    {
                        "activation_request_id": (
                            "request-001"
                        ),
                        "setup_activation_id": (
                            "setup-activation-001"
                        ),
                        "customer_id": "customer-001",
                        "status": "ACTIVE",
                        "deployment_id": None,
                    },
                    {
                        "activation_request_id": (
                            "request-001"
                        ),
                        "setup_activation_id": (
                            "setup-activation-002"
                        ),
                        "customer_id": "customer-001",
                        "status": "ACTIVE",
                        "deployment_id": None,
                    },
                ],
            }
        ),
        encoding="utf-8",
    )

    with pytest.raises(
        ValueError,
        match="Duplicate setup activation request",
    ):
        CustomerSetupActivationStore(
            path
        )


def test_restore_rejects_duplicate_activation_id(
    tmp_path: Path,
) -> None:
    path = (
        tmp_path
        / "activations.json"
    )

    path.write_text(
        json.dumps(
            {
                "version": 1,
                "records": [
                    {
                        "activation_request_id": (
                            "request-001"
                        ),
                        "setup_activation_id": (
                            "setup-activation-001"
                        ),
                        "customer_id": "customer-001",
                        "status": "ACTIVE",
                        "deployment_id": None,
                    },
                    {
                        "activation_request_id": (
                            "request-002"
                        ),
                        "setup_activation_id": (
                            "setup-activation-001"
                        ),
                        "customer_id": "customer-001",
                        "status": "ACTIVE",
                        "deployment_id": None,
                    },
                ],
            }
        ),
        encoding="utf-8",
    )

    with pytest.raises(
        ValueError,
        match="Duplicate setup activation identity",
    ):
        CustomerSetupActivationStore(
            path
        )


def test_restore_rejects_duplicate_deployment_binding(
    tmp_path: Path,
) -> None:
    path = (
        tmp_path
        / "activations.json"
    )

    path.write_text(
        json.dumps(
            {
                "version": 1,
                "records": [
                    {
                        "activation_request_id": (
                            "request-001"
                        ),
                        "setup_activation_id": (
                            "setup-activation-001"
                        ),
                        "customer_id": "customer-001",
                        "status": "BOUND",
                        "deployment_id": "deployment-001",
                    },
                    {
                        "activation_request_id": (
                            "request-002"
                        ),
                        "setup_activation_id": (
                            "setup-activation-002"
                        ),
                        "customer_id": "customer-001",
                        "status": "BOUND",
                        "deployment_id": "deployment-001",
                    },
                ],
            }
        ),
        encoding="utf-8",
    )

    with pytest.raises(
        ValueError,
        match=(
            "Deployment is bound to multiple "
            "setup activations"
        ),
    ):
        CustomerSetupActivationStore(
            path
        )


def test_service_requires_correct_owner_types(
    tmp_path: Path,
) -> None:
    identity_registry = CustomerIdentityRegistry(
        tmp_path
        / "identities.json"
    )
    identity_registry.initialize_empty()

    deployment_registry = CustomerDeploymentRegistry(
        tmp_path
        / "deployments.json"
    )
    deployment_registry.initialize_empty()

    activation_store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    activation_store.initialize_empty()

    with pytest.raises(
        TypeError,
        match="activation_store",
    ):
        CustomerSetupActivationService(
            activation_store=object(),
            customer_identity_registry=identity_registry,
            deployment_registry=deployment_registry,
        )

    with pytest.raises(
        TypeError,
        match="customer_identity_registry",
    ):
        CustomerSetupActivationService(
            activation_store=activation_store,
            customer_identity_registry=object(),
            deployment_registry=deployment_registry,
        )

    with pytest.raises(
        TypeError,
        match="deployment_registry",
    ):
        CustomerSetupActivationService(
            activation_store=activation_store,
            customer_identity_registry=identity_registry,
            deployment_registry=object(),
        )


def test_service_requires_ready_sources(
    tmp_path: Path,
) -> None:
    identity_registry = CustomerIdentityRegistry(
        tmp_path
        / "identities.json"
    )

    deployment_registry = CustomerDeploymentRegistry(
        tmp_path
        / "deployments.json"
    )

    activation_store = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )

    identity_registry.initialize_empty()
    deployment_registry.initialize_empty()

    with pytest.raises(
        RuntimeError,
        match="activation store",
    ):
        CustomerSetupActivationService(
            activation_store=activation_store,
            customer_identity_registry=identity_registry,
            deployment_registry=deployment_registry,
        )

    activation_store.initialize_empty()

    unready_identity = CustomerIdentityRegistry(
        tmp_path
        / "unready-identities.json"
    )

    with pytest.raises(
        RuntimeError,
        match="identity registry",
    ):
        CustomerSetupActivationService(
            activation_store=activation_store,
            customer_identity_registry=unready_identity,
            deployment_registry=deployment_registry,
        )

    unready_deployments = CustomerDeploymentRegistry(
        tmp_path
        / "unready-deployments.json"
    )

    with pytest.raises(
        RuntimeError,
        match="deployment registry",
    ):
        CustomerSetupActivationService(
            activation_store=activation_store,
            customer_identity_registry=identity_registry,
            deployment_registry=unready_deployments,
        )


def test_service_activates_registered_customer(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        _,
        activation_store,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    result = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    assert (
        result.activation_request_id
        == "activation-001"
    )
    assert result.customer_id == "customer-001"
    assert result.setup_activation_id.startswith(
        "setup-activation-"
    )
    assert (
        result.status
        is CustomerSetupActivationStatus.ACTIVE
    )
    assert result.deployment_id is None
    assert activation_store.size() == 1


def test_service_rejects_unknown_customer(
    tmp_path: Path,
) -> None:
    _, _, activation_store, service = (
        build_environment(
            tmp_path
        )
    )

    with pytest.raises(
        ValueError,
        match=(
            "Customer identity is not registered"
        ),
    ):
        service.activate(
            activation_request_id="activation-001",
            customer_id="customer-missing",
        )

    assert activation_store.size() == 0


def test_service_activation_retry_returns_same_right(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        _,
        activation_store,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    first = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    second = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    assert second == first
    assert activation_store.size() == 1


def test_service_request_reuse_by_other_customer_fails_closed(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        _,
        activation_store,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry,
        "customer-001",
    )

    register_customer(
        identity_registry,
        "customer-002",
    )

    first = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    with pytest.raises(
        ValueError,
        match="different customer",
    ):
        service.activate(
            activation_request_id="activation-001",
            customer_id="customer-002",
        )

    assert activation_store.size() == 1

    stored = activation_store.get(
        setup_activation_id=(
            first.setup_activation_id
        )
    )

    assert stored is not None
    assert stored.customer_id == "customer-001"


def test_one_customer_may_receive_multiple_setup_rights(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        _,
        activation_store,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    first = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    second = service.activate(
        activation_request_id="activation-002",
        customer_id="customer-001",
    )

    assert (
        first.setup_activation_id
        != second.setup_activation_id
    )
    assert activation_store.size() == 2


def test_activation_retry_does_not_reactivate_suspended_right(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        _,
        _,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    active = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    suspended = service.suspend(
        setup_activation_id=(
            active.setup_activation_id
        )
    )

    retried = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    assert retried == suspended
    assert (
        retried.status
        is CustomerSetupActivationStatus.SUSPENDED
    )

    reactivated = service.reactivate(
        setup_activation_id=(
            active.setup_activation_id
        )
    )

    assert (
        reactivated.status
        is CustomerSetupActivationStatus.ACTIVE
    )


def test_service_bind_requires_authoritative_deployment(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        _,
        _,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    active = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    with pytest.raises(
        ValueError,
        match="Unknown customer deployment",
    ):
        service.bind(
            setup_activation_id=(
                active.setup_activation_id
            ),
            deployment_id="deployment-missing",
        )


def test_service_bind_rejects_cross_customer_deployment(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        deployment_registry,
        _,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry,
        "customer-001",
    )

    register_customer(
        identity_registry,
        "customer-002",
    )

    register_deployment(
        deployment_registry,
        customer_id="customer-002",
        deployment_id="deployment-002",
        agent_id="trusted-agent-002",
    )

    active = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    with pytest.raises(
        ValueError,
        match="different customer",
    ):
        service.bind(
            setup_activation_id=(
                active.setup_activation_id
            ),
            deployment_id="deployment-002",
        )


def test_service_binds_matching_customer_deployment(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        deployment_registry,
        activation_store,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    deployment = register_deployment(
        deployment_registry
    )

    active = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    bound = service.bind(
        setup_activation_id=(
            active.setup_activation_id
        ),
        deployment_id=(
            deployment.deployment_id
        ),
    )

    assert (
        bound.status
        is CustomerSetupActivationStatus.BOUND
    )
    assert (
        bound.deployment_id
        == deployment.deployment_id
    )

    stored = activation_store.get_by_deployment_id(
        deployment_id=deployment.deployment_id
    )

    assert stored is not None
    assert (
        stored.setup_activation_id
        == active.setup_activation_id
    )


def test_service_bound_retry_is_idempotent(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        deployment_registry,
        _,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    deployment = register_deployment(
        deployment_registry
    )

    active = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    first = service.bind(
        setup_activation_id=(
            active.setup_activation_id
        ),
        deployment_id=deployment.deployment_id,
    )

    second = service.bind(
        setup_activation_id=(
            active.setup_activation_id
        ),
        deployment_id=deployment.deployment_id,
    )

    assert second == first


def test_activation_retry_preserves_bound_truth(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        deployment_registry,
        _,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    deployment = register_deployment(
        deployment_registry
    )

    active = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    bound = service.bind(
        setup_activation_id=(
            active.setup_activation_id
        ),
        deployment_id=deployment.deployment_id,
    )

    retried = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    assert retried == bound
    assert (
        retried.status
        is CustomerSetupActivationStatus.BOUND
    )
    assert (
        retried.deployment_id
        == deployment.deployment_id
    )


def test_two_setup_rights_cannot_consume_same_deployment(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        deployment_registry,
        _,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    deployment = register_deployment(
        deployment_registry
    )

    first = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    second = service.activate(
        activation_request_id="activation-002",
        customer_id="customer-001",
    )

    service.bind(
        setup_activation_id=(
            first.setup_activation_id
        ),
        deployment_id=deployment.deployment_id,
    )

    with pytest.raises(
        ValueError,
        match=(
            "Deployment is already bound to another "
            "setup activation"
        ),
    ):
        service.bind(
            setup_activation_id=(
                second.setup_activation_id
            ),
            deployment_id=deployment.deployment_id,
        )


def test_service_avoids_generated_activation_id_collision(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    (
        identity_registry,
        _,
        activation_store,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    activation_store.register(
        CustomerSetupActivationRecord(
            activation_request_id=(
                "existing-request"
            ),
            setup_activation_id=(
                "setup-activation-collision"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    generated = iter(
        [
            SimpleNamespace(
                hex="collision"
            ),
            SimpleNamespace(
                hex="fresh"
            ),
        ]
    )

    monkeypatch.setattr(
        activation_module.uuid,
        "uuid4",
        lambda: next(
            generated
        ),
    )

    result = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    assert (
        result.setup_activation_id
        == "setup-activation-fresh"
    )


def test_service_fails_when_unique_activation_id_cannot_be_generated(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    (
        identity_registry,
        _,
        activation_store,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    activation_store.register(
        CustomerSetupActivationRecord(
            activation_request_id=(
                "existing-request"
            ),
            setup_activation_id=(
                "setup-activation-collision"
            ),
            customer_id="customer-001",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    monkeypatch.setattr(
        activation_module.uuid,
        "uuid4",
        lambda: SimpleNamespace(
            hex="collision"
        ),
    )

    with pytest.raises(
        RuntimeError,
        match=(
            "Unable to generate unique setup activation "
            "identity"
        ),
    ):
        service.activate(
            activation_request_id="activation-001",
            customer_id="customer-001",
        )


def test_service_restart_recovers_active_setup_right(
    tmp_path: Path,
) -> None:
    identity_path = (
        tmp_path
        / "identities.json"
    )

    deployment_path = (
        tmp_path
        / "deployments.json"
    )

    activation_path = (
        tmp_path
        / "activations.json"
    )

    identities = CustomerIdentityRegistry(
        identity_path
    )
    identities.initialize_empty()
    register_customer(
        identities
    )

    deployments = CustomerDeploymentRegistry(
        deployment_path
    )
    deployments.initialize_empty()

    activations = CustomerSetupActivationStore(
        activation_path
    )
    activations.initialize_empty()

    service = CustomerSetupActivationService(
        activation_store=activations,
        customer_identity_registry=identities,
        deployment_registry=deployments,
    )

    first = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    restarted_service = CustomerSetupActivationService(
        activation_store=(
            CustomerSetupActivationStore(
                activation_path
            )
        ),
        customer_identity_registry=(
            CustomerIdentityRegistry(
                identity_path
            )
        ),
        deployment_registry=(
            CustomerDeploymentRegistry(
                deployment_path
            )
        ),
    )

    recovered = restarted_service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    assert recovered == first


def test_service_restart_recovers_bound_setup_right(
    tmp_path: Path,
) -> None:
    identity_path = (
        tmp_path
        / "identities.json"
    )

    deployment_path = (
        tmp_path
        / "deployments.json"
    )

    activation_path = (
        tmp_path
        / "activations.json"
    )

    identities = CustomerIdentityRegistry(
        identity_path
    )
    identities.initialize_empty()
    register_customer(
        identities
    )

    deployments = CustomerDeploymentRegistry(
        deployment_path
    )
    deployments.initialize_empty()

    deployment = register_deployment(
        deployments
    )

    activations = CustomerSetupActivationStore(
        activation_path
    )
    activations.initialize_empty()

    service = CustomerSetupActivationService(
        activation_store=activations,
        customer_identity_registry=identities,
        deployment_registry=deployments,
    )

    active = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    bound = service.bind(
        setup_activation_id=(
            active.setup_activation_id
        ),
        deployment_id=deployment.deployment_id,
    )

    restarted_service = CustomerSetupActivationService(
        activation_store=(
            CustomerSetupActivationStore(
                activation_path
            )
        ),
        customer_identity_registry=(
            CustomerIdentityRegistry(
                identity_path
            )
        ),
        deployment_registry=(
            CustomerDeploymentRegistry(
                deployment_path
            )
        ),
    )

    recovered = restarted_service.get(
        setup_activation_id=(
            bound.setup_activation_id
        )
    )

    assert recovered == bound


def test_service_restore_rejects_unknown_customer_truth(
    tmp_path: Path,
) -> None:
    identities = CustomerIdentityRegistry(
        tmp_path
        / "identities.json"
    )
    identities.initialize_empty()

    deployments = CustomerDeploymentRegistry(
        tmp_path
        / "deployments.json"
    )
    deployments.initialize_empty()

    activations = CustomerSetupActivationStore(
        tmp_path
        / "activations.json"
    )
    activations.initialize_empty()

    activations.register(
        CustomerSetupActivationRecord(
            activation_request_id="request-001",
            setup_activation_id=(
                "setup-activation-001"
            ),
            customer_id="customer-missing",
            status=(
                CustomerSetupActivationStatus.ACTIVE
            ),
        )
    )

    with pytest.raises(
        RuntimeError,
        match="unknown customer identity",
    ):
        CustomerSetupActivationService(
            activation_store=activations,
            customer_identity_registry=identities,
            deployment_registry=deployments,
        )


def test_service_restore_rejects_unknown_bound_deployment(
    tmp_path: Path,
) -> None:
    identities = CustomerIdentityRegistry(
        tmp_path
        / "identities.json"
    )
    identities.initialize_empty()
    register_customer(
        identities
    )

    deployments = CustomerDeploymentRegistry(
        tmp_path
        / "deployments.json"
    )
    deployments.initialize_empty()

    activation_path = (
        tmp_path
        / "activations.json"
    )

    activation_path.write_text(
        json.dumps(
            {
                "version": 1,
                "records": [
                    {
                        "activation_request_id": (
                            "request-001"
                        ),
                        "setup_activation_id": (
                            "setup-activation-001"
                        ),
                        "customer_id": "customer-001",
                        "status": "BOUND",
                        "deployment_id": (
                            "deployment-missing"
                        ),
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    activations = CustomerSetupActivationStore(
        activation_path
    )

    with pytest.raises(
        RuntimeError,
        match="unknown customer deployment",
    ):
        CustomerSetupActivationService(
            activation_store=activations,
            customer_identity_registry=identities,
            deployment_registry=deployments,
        )


def test_service_restore_rejects_cross_customer_bound_truth(
    tmp_path: Path,
) -> None:
    identities = CustomerIdentityRegistry(
        tmp_path
        / "identities.json"
    )
    identities.initialize_empty()

    register_customer(
        identities,
        "customer-001",
    )
    register_customer(
        identities,
        "customer-002",
    )

    deployments = CustomerDeploymentRegistry(
        tmp_path
        / "deployments.json"
    )
    deployments.initialize_empty()

    register_deployment(
        deployments,
        customer_id="customer-002",
        deployment_id="deployment-002",
        agent_id="trusted-agent-002",
    )

    activation_path = (
        tmp_path
        / "activations.json"
    )

    activation_path.write_text(
        json.dumps(
            {
                "version": 1,
                "records": [
                    {
                        "activation_request_id": (
                            "request-001"
                        ),
                        "setup_activation_id": (
                            "setup-activation-001"
                        ),
                        "customer_id": "customer-001",
                        "status": "BOUND",
                        "deployment_id": (
                            "deployment-002"
                        ),
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    activations = CustomerSetupActivationStore(
        activation_path
    )

    with pytest.raises(
        RuntimeError,
        match="ownership is inconsistent",
    ):
        CustomerSetupActivationService(
            activation_store=activations,
            customer_identity_registry=identities,
            deployment_registry=deployments,
        )


def test_persistence_contains_only_setup_right_truth(
    tmp_path: Path,
) -> None:
    (
        identity_registry,
        deployment_registry,
        activation_store,
        service,
    ) = build_environment(
        tmp_path
    )

    register_customer(
        identity_registry
    )

    deployment = register_deployment(
        deployment_registry
    )

    active = service.activate(
        activation_request_id="activation-001",
        customer_id="customer-001",
    )

    service.bind(
        setup_activation_id=(
            active.setup_activation_id
        ),
        deployment_id=deployment.deployment_id,
    )

    payload = json.loads(
        activation_store.storage_path.read_text(
            encoding="utf-8",
        )
    )

    assert set(
        payload
    ) == {
        "version",
        "records",
    }

    assert len(
        payload["records"]
    ) == 1

    record = payload[
        "records"
    ][0]

    assert set(
        record
    ) == {
        "activation_request_id",
        "setup_activation_id",
        "customer_id",
        "status",
        "deployment_id",
    }

    forbidden_fields = {
        "payment_id",
        "transaction_id",
        "subscription_id",
        "amount",
        "currency",
        "email",
        "phone",
        "password",
        "account_fingerprint",
        "agent_id",
        "credential_id",
        "access_credential",
        "secret",
        "package_path",
        "package_root",
        "entitlement",
    }

    assert forbidden_fields.isdisjoint(
        record
    )


def test_activate_contract_accepts_no_payment_or_deployment_inputs() -> None:
    parameters = inspect.signature(
        CustomerSetupActivationService.activate
    ).parameters

    assert set(
        parameters
    ) == {
        "self",
        "activation_request_id",
        "customer_id",
    }

    forbidden = {
        "payment_id",
        "transaction_id",
        "subscription_id",
        "amount",
        "currency",
        "deployment_id",
        "agent_id",
        "account_fingerprint",
        "credential",
        "secret",
        "package",
        "entitlement",
    }

    assert forbidden.isdisjoint(
        parameters
    )


def test_bind_contract_accepts_only_activation_and_deployment_identity() -> None:
    parameters = inspect.signature(
        CustomerSetupActivationService.bind
    ).parameters

    assert set(
        parameters
    ) == {
        "self",
        "setup_activation_id",
        "deployment_id",
    }